#!/bin/bash
# Rebuild Ornament.js from CodinCod's own ornament sources.
#
# The shoal is not reimplemented here. `assets/js/ornament/` in the CodinCod
# repository is deliberately free of the DOM: `shoal.ts` decides where a fish
# goes, `fish_shape.ts` draws one, `perlin.ts` supplies the field, and the half
# that touches a browser lives apart in `water.ts`. That split is what lets a
# second renderer exist at all, so this takes the simulation as it is, bundles
# it for Qt's JavaScript engine, and leaves `Background.qml` to be the desktop's
# answer to `water.ts`.
#
# Run this after changing the ornament on the site, and the desktop swims the
# same way.

set -euo pipefail

CODINCOD="${CODINCOD_DIR:-$HOME/Documents/projects/codincodv2}"
ORNAMENT="$CODINCOD/assets/js/ornament"
ESBUILD="${ESBUILD_BIN:-$CODINCOD/_build/esbuild-linux-x64}"
OUT="$(cd "$(dirname "$0")" && pwd)/Ornament.js"

[[ -d $ORNAMENT ]] || { echo "no ornament sources at $ORNAMENT" >&2; exit 1; }
[[ -x $ESBUILD ]] || { echo "no esbuild at $ESBUILD" >&2; exit 1; }

entry=$(mktemp -d)
trap 'rm -rf "$entry"' EXIT

cat >"$entry/entry.ts" <<ENTRY
export { createDrift } from "$ORNAMENT/drift.ts"
export { frameAt, SPAN, STEPS } from "$ORNAMENT/fish_shape.ts"
export { createRays, SPREAD } from "$ORNAMENT/rays.ts"
export { createShoal, freshSeed } from "$ORNAMENT/shoal.ts"
ENTRY

# Qt's engine wants one script with no module syntax in it. `.pragma library`
# makes the bundle shared rather than re-instantiated per screen, which matters
# because `fish_shape.ts` caches every drawing it builds.
#
# The target is es2017 because Qt's engine is not a browser and is behind one.
# esbuild rewrites the syntax it can (`??`, `?.`) and leaves library methods
# alone, so `Array.prototype.at` is shimmed rather than assumed; `shoal.ts`
# reaches for it when a shoal is thinned to fit a smaller box.
#
# The footer lifts the exports out of the IIFE's namespace so the QML side can
# say `Ornament.createShoal` rather than `Ornament.Ornament.createShoal`.
"$ESBUILD" "$entry/entry.ts" \
  --bundle \
  --format=iife \
  --global-name=__ornament \
  --target=es2017 \
  --legal-comments=none \
  --banner:js='.pragma library
// Generated by build-ornament.sh from the CodinCod repository. Do not edit.
if (!Array.prototype.at) {
  Array.prototype.at = function (index) {
    var i = Math.trunc(index) || 0
    if (i < 0) i += this.length
    return i < 0 || i >= this.length ? undefined : this[i]
  }
}' \
  --footer:js='var createDrift = __ornament.createDrift
var createRays = __ornament.createRays
var createShoal = __ornament.createShoal
var frameAt = __ornament.frameAt
var freshSeed = __ornament.freshSeed
var SPAN = __ornament.SPAN
var SPREAD = __ornament.SPREAD
var STEPS = __ornament.STEPS' \
  --outfile="$OUT"

echo "wrote $OUT"
