#!/bin/bash
# Rebuild Ornament.js from CodinCod's own ornament sources.
#
# The shoal is not reimplemented here. `assets/js/ornament/` in the CodinCod
# repository is deliberately free of the DOM: `shoal.ts` decides where a fish
# goes, `fish_shape.ts` draws one, `perlin.ts` supplies the field, and the half
# that touches a browser lives apart in `water.ts`. That split is what lets a
# second renderer exist at all, so this takes the simulation as it is, bundles
# it for Qt's JavaScript engine, and leaves `Background.qml` to be the desktop's
# answer to `water.ts`.
#
# Run this after changing the ornament on the site, and the desktop swims the
# same way.

set -euo pipefail

CODINCOD="${CODINCOD_DIR:-$HOME/Documents/projects/codincodv2}"
ORNAMENT="$CODINCOD/assets/js/ornament"
ESBUILD="${ESBUILD_BIN:-$CODINCOD/_build/esbuild-linux-x64}"
OUT="$(cd "$(dirname "$0")" && pwd)/Ornament.js"

[[ -d $ORNAMENT ]] || { echo "no ornament sources at $ORNAMENT" >&2; exit 1; }
[[ -x $ESBUILD ]] || { echo "no esbuild at $ESBUILD" >&2; exit 1; }

# Beside the bundle rather than in a temp directory, and the reason is
# reproducibility rather than tidiness. esbuild writes the entry file's path
# into the output as a comment, relative to the outfile, so a `mktemp -d` name
# lands in the bundle and two builds of identical sources differ by one line.
#
# That costs the only cheap check there is on whether a committed bundle
# matches the sources it claims to come from: rebuild it and see whether git
# says the tree is dirty. With a random name in there the answer is always yes,
# which is a false alarm that trains everybody to ignore a real one.
#
# The directory is removed on the way out, whichever way out it is.
entry="$(cd "$(dirname "$0")" && pwd)/.ornament-entry"
rm -rf "$entry"
mkdir -p "$entry"
trap 'rm -rf "$entry"' EXIT

# What the desktop takes from each module, as `module export export ...`. The
# entry file and the footer that flattens the bundle are both generated from
# this, because keeping two hand-written lists in step is a job nobody does
# until something is quietly missing from the scene.
WANTED=(
  "biome abreast createBiome"
  "cephalopods OCTOPUS_HEAD createCephalopods octopusArms octopusHead squidArms squidBody"
  "crags SPRIGS createCrags"
  "drift createDrift"
  "fish_shape frameAt SPAN STEPS"
  "flora CORAL createFlora"
  "nemos createNemos"
  "passers FROTH_MOST HULL PING_RINGS SCREWS SUBMARINE SUB_SCREW createPassers ringAt"
  "plenty thriving"
  "rays SPREAD createRays fade"
  "reef KINDS SHAPES createReef"
  "relics BLOCK_CARD BLOCK_LINES CHEST_BANDS CHEST_BODY CHEST_LOCK LAPTOP_BASE LAPTOP_LINES LAPTOP_SCREEN SMOKER SMOKER_LIP WRECK WRECK_SPAR createRelics"
  "seabed createSeabed"
  "shoal SPECIES WILD createShoal daySeed freshSeed"
  "sun sunNow"
  "swarm createSwarm"
  "visitors BODIES createVisitors"
  "walkers CRAB_SHELL crabLegs crabShell createWalkers starfishBody"
)

: >"$entry/entry.ts"
footer=""

for line in "${WANTED[@]}"; do
  read -ra parts <<<"$line"
  module=${parts[0]}
  names=("${parts[@]:1}")

  printf 'export { %s } from "%s/%s.ts"\n' \
    "$(IFS=,; echo "${names[*]}")" "$ORNAMENT" "$module" >>"$entry/entry.ts"

  for name in "${names[@]}"; do
    footer+="var $name = __ornament.$name"$'\n'
  done
done

# Qt's engine wants one script with no module syntax in it. `.pragma library`
# makes the bundle shared rather than re-instantiated per screen, which matters
# because `fish_shape.ts` caches every drawing it builds.
#
# The target is es2017 because Qt's engine is not a browser and is behind one.
# esbuild rewrites the syntax it can (`??`, `?.`) and leaves library methods
# alone, so `Array.prototype.at` is shimmed rather than assumed; `shoal.ts`
# reaches for it when a shoal is thinned to fit a smaller box.
#
# The footer lifts the exports out of the IIFE's namespace so the QML side can
# say `Ornament.createShoal` rather than `Ornament.Ornament.createShoal`.
"$ESBUILD" "$entry/entry.ts" \
  --bundle \
  --format=iife \
  --global-name=__ornament \
  --target=es2017 \
  --legal-comments=none \
  --banner:js='.pragma library
// Generated by build-ornament.sh from the CodinCod repository. Do not edit.
if (!Array.prototype.at) {
  Array.prototype.at = function (index) {
    var i = Math.trunc(index) || 0
    if (i < 0) i += this.length
    return i < 0 || i >= this.length ? undefined : this[i]
  }
}' \
  --footer:js="$footer" \
  --outfile="$OUT"

echo "wrote $OUT ($(grep -c . <<<"$footer") exports)"
