.pragma library
// Generated by build-ornament.sh from the CodinCod repository. Do not edit.
if (!Array.prototype.at) {
  Array.prototype.at = function (index) {
    var i = Math.trunc(index) || 0
    if (i < 0) i += this.length
    return i < 0 || i >= this.length ? undefined : this[i]
  }
}
var __ornament = (() => {
  var __defProp = Object.defineProperty;
  var __defProps = Object.defineProperties;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __getOwnPropSymbols = Object.getOwnPropertySymbols;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __propIsEnum = Object.prototype.propertyIsEnumerable;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __spreadValues = (a, b) => {
    for (var prop in b || (b = {}))
      if (__hasOwnProp.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    if (__getOwnPropSymbols)
      for (var prop of __getOwnPropSymbols(b)) {
        if (__propIsEnum.call(b, prop))
          __defNormalProp(a, prop, b[prop]);
      }
    return a;
  };
  var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // ../../../../../../tmp/tmp.Ap3pF4iEnU/entry.ts
  var entry_exports = {};
  __export(entry_exports, {
    BLOCK_CARD: () => BLOCK_CARD,
    BLOCK_LINES: () => BLOCK_LINES,
    CHEST_BANDS: () => CHEST_BANDS,
    CHEST_BODY: () => CHEST_BODY,
    CHEST_LOCK: () => CHEST_LOCK,
    CORAL: () => CORAL,
    HULL: () => HULL,
    LAPTOP_BASE: () => LAPTOP_BASE,
    LAPTOP_LINES: () => LAPTOP_LINES,
    LAPTOP_SCREEN: () => LAPTOP_SCREEN,
    OCTOPUS_HEAD: () => OCTOPUS_HEAD,
    PING_RINGS: () => PING_RINGS,
    SCREWS: () => SCREWS,
    SMOKER: () => SMOKER,
    SMOKER_LIP: () => SMOKER_LIP,
    SPAN: () => SPAN,
    SPECIES: () => SPECIES,
    SPREAD: () => SPREAD,
    STEPS: () => STEPS,
    SUBMARINE: () => SUBMARINE,
    SUB_SCREW: () => SUB_SCREW,
    WAKE: () => WAKE,
    WILD: () => WILD,
    WRECK: () => WRECK,
    WRECK_SPAR: () => WRECK_SPAR,
    createCephalopods: () => createCephalopods,
    createDrift: () => createDrift,
    createFlora: () => createFlora,
    createPassers: () => createPassers,
    createRays: () => createRays,
    createRelics: () => createRelics,
    createSeabed: () => createSeabed,
    createShoal: () => createShoal,
    daySeed: () => daySeed,
    frameAt: () => frameAt,
    freshSeed: () => freshSeed,
    octopusArms: () => octopusArms,
    ringAt: () => ringAt,
    squidArms: () => squidArms,
    squidBody: () => squidBody,
    sunNow: () => sunNow
  });

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/perlin.ts
  var SIZE = 256;
  var MASK = SIZE - 1;
  var NORMALISE = Math.SQRT2;
  function makeRandom(seed) {
    let state = seed | 0 || 1;
    return () => {
      state ^= state << 13;
      state ^= state >>> 17;
      state ^= state << 5;
      return (state >>> 0) / 4294967296;
    };
  }
  function stir(from) {
    let seed = from >>> 0;
    seed = Math.imul(seed ^ seed >>> 16, 73244475) >>> 0;
    return (seed ^ seed >>> 16) >>> 0;
  }
  function makeNoise2(seed) {
    const random = makeRandom(seed);
    const permutation = new Int32Array(SIZE + SIZE + 2);
    const gradientX = new Float64Array(SIZE + SIZE + 2);
    const gradientY = new Float64Array(SIZE + SIZE + 2);
    for (let i = 0; i < SIZE; i++) {
      permutation[i] = i;
      const angle = random() * Math.PI * 2;
      gradientX[i] = Math.cos(angle);
      gradientY[i] = Math.sin(angle);
    }
    for (let i = SIZE - 1; i > 0; i--) {
      const j = Math.floor(random() * (i + 1));
      const held = permutation[i];
      permutation[i] = permutation[j];
      permutation[j] = held;
    }
    for (let i = 0; i < SIZE + 2; i++) {
      permutation[SIZE + i] = permutation[i];
      gradientX[SIZE + i] = gradientX[i];
      gradientY[SIZE + i] = gradientY[i];
    }
    const dot = (gradient, x, y) => gradientX[gradient] * x + gradientY[gradient] * y;
    return (x, y) => {
      const cellX = Math.floor(x);
      const cellY = Math.floor(y);
      const dx0 = x - cellX;
      const dy0 = y - cellY;
      const dx1 = dx0 - 1;
      const dy1 = dy0 - 1;
      const bx0 = cellX & MASK;
      const by0 = cellY & MASK;
      const bx1 = bx0 + 1 & MASK;
      const by1 = by0 + 1 & MASK;
      const i = permutation[bx0];
      const j = permutation[bx1];
      const g00 = permutation[i + by0];
      const g10 = permutation[j + by0];
      const g01 = permutation[i + by1];
      const g11 = permutation[j + by1];
      const sx = sCurve(dx0);
      const sy = sCurve(dy0);
      const top = lerp(sx, dot(g00, dx0, dy0), dot(g10, dx1, dy0));
      const bottom = lerp(sx, dot(g01, dx0, dy1), dot(g11, dx1, dy1));
      return lerp(sy, top, bottom) * NORMALISE;
    };
  }
  function sCurve(t) {
    return t * t * (3 - 2 * t);
  }
  function lerp(t, a, b) {
    return a + t * (b - a);
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/shoal.ts
  var SPECIES = {
    /** The one that was here first. Everything else is described against it. */
    cruiser: { bill: 0, deep: 0.52, girth: 1, hold: 1, pace: 1, pitch: 1, stride: 1, verve: 0 },
    /** Small, quick, and never going anywhere for long. */
    darter: {
      bill: 0,
      deep: 0.58,
      girth: 0.42,
      hold: 0.3,
      pace: 1.5,
      pitch: 1.4,
      stride: 0.58,
      verve: 1
    },
    /** Long, slow and far back, crossing the murk on one heading. */
    drifter: {
      bill: 0,
      deep: 0.2,
      girth: 2.1,
      hold: 4.5,
      pace: 0.6,
      pitch: 0.45,
      stride: 1.7,
      verve: 0
    },
    /** Comes in twos and holds station with the other. See `Fish.mate`. */
    escort: {
      bill: 0,
      deep: 0.62,
      girth: 0.72,
      hold: 1.4,
      pace: 1.1,
      pitch: 0.9,
      stride: 0.85,
      verve: 0
    },
    /**
     * Big, quick, near the front of the water, and holding one line for a long
     * time. The bill is most of it, but the rest has to agree with the bill: an
     * animal built like that and pottering about would read as a drawing error.
     *
     * A long stride with real bursts in it, which is what a thunniform swimmer
     * does. It hardly bends: everything happens at the tail, so the pitch is held
     * shallow and the body reads as a rigid thing being driven.
     */
    swordfish: {
      bill: 1,
      deep: 0.72,
      girth: 1.85,
      hold: 3.2,
      pace: 1.55,
      pitch: 0.55,
      stride: 1.5,
      verve: 0.45
    }
  };
  var WILD = {
    cruiser: 5,
    darter: 4,
    drifter: 1,
    escort: 2,
    swordfish: 1
  };
  var MIN_SHOAL = 1;
  var FIELD_CELLS = 3.6;
  var DRIFT = 0.06;
  var CRUISE = 1.05;
  var STRIDE = 0.7;
  var DART = 3.4;
  var TURN = 0.85;
  var TURN_STARTLED = 3.4;
  var HASTE = 2.2;
  var MAX_PITCH = 0.6;
  var EDGE_REACH = 0.18;
  var EDGE_PUSH = 0.9;
  var SWEEP = 1.1;
  var HOMING = 0.34;
  var HOLD_LEAST = 1.6;
  var HOLD_SPAN = 6.5;
  var BEND = 0.85;
  var WOBBLE = 0.18;
  var MARGIN = 0.8;
  var JOIN_REACH = 5;
  var NEIGHBOUR_REACH = 70;
  var NEIGHBOUR_PUSH = 0.8;
  var FLEE_REACH = 340;
  var FLEE_PUSH = 3.6;
  var PANIC = 0.62;
  var LOOK_DELAY = 1.1;
  var LOOK_REACH = 320;
  var LOOK_PUSH = 2.2;
  var LEAN_PUSH = 0.5;
  var LOOK_SPAN = 13;
  var LOOK_REST = 5;
  var STANDOFF = 70;
  var HOVER = 0.45;
  var LOSE_INTEREST = 1.8;
  var DEPTH_SWING = 0.46;
  var DEPTH_DRIFT = 0.035;
  var DEPTH_NEAR = 1;
  var DEPTH_FAR = 0.06;
  var DEPTH_EASE = 0.5;
  var DEPTH_DIVE = 1.4;
  var DIVE = 0.35;
  var RISE = 0.94;
  var DEPTH_SIZE = 0.6;
  var SURGE = 0.26;
  var SPURT_SLOWEST = 0.9;
  var SPURT_FASTEST = 1.9;
  var SPURT_SHARE = 0.32;
  var SPURT_PUSH = 2.4;
  var SPURT_COAST = 0.22;
  var STATION_BACK = 1.3;
  var STATION_SIDE = 0.55;
  var STATION_PUSH = 1.6;
  var STATION_CATCH = 0.55;
  var STATION_SLOWEST = 0.35;
  var STATION_BRISKEST = 2.1;
  var SLOWEST = 0.45;
  var FASTEST = 1.9;
  var LEISURE = 2;
  var SHORTEST = 34;
  var LONGEST = 58;
  function freshSeed(from = 0) {
    return stir(Date.now() ^ from);
  }
  function daySeed(now = /* @__PURE__ */ new Date(), from = 0) {
    const day = now.getFullYear() * 1e4 + (now.getMonth() + 1) * 100 + now.getDate();
    return stir(day ^ from) | 0;
  }
  function createShoal(options) {
    var _a, _b, _c;
    const noise = makeNoise2(options.seed);
    const depths = makeNoise2(options.seed ^ 40503);
    const random = makeRandom(options.seed ^ 24381);
    let width = Math.max(1, options.width);
    let height = Math.max(1, options.height);
    let drift = 0;
    let sank = 0;
    let still = 0;
    let attentive = null;
    let visit = 0;
    let rest = 0;
    let last = null;
    const cruise = (_a = options.cruise) != null ? _a : CRUISE;
    const shortest = (_b = options.shortest) != null ? _b : SHORTEST;
    const longest = (_c = options.longest) != null ? _c : LONGEST;
    const mix2 = weigh(options.species);
    const born = () => spawn(random, draw(mix2, random), { cruise, height, longest, shortest, width });
    const fish = Array.from({ length: Math.max(MIN_SHOAL, options.count) }, born);
    pair(fish);
    function renew(at) {
      const going = fish[at];
      if (!going) return;
      const lead = going.mate;
      if (lead && fish.includes(lead)) {
        const x = lead.x - lead.facing * lead.size * STATION_BACK;
        if (gone(x, width, going.size)) {
          going.x = x;
          going.y = lead.y + lead.size * STATION_SIDE;
          return;
        }
      }
      const made = born();
      made.x = made.facing > 0 ? -made.size * MARGIN : width + made.size * MARGIN;
      fish[at] = made;
      if (attentive === going) attentive = null;
      if (last === going) last = null;
      for (const one of fish) if (one.mate === going) one.mate = null;
    }
    return {
      get attentive() {
        return attentive;
      },
      fish,
      resize(nextWidth, nextHeight, count) {
        const scaleX = Math.max(1, nextWidth) / width;
        const scaleY = Math.max(1, nextHeight) / height;
        width = Math.max(1, nextWidth);
        height = Math.max(1, nextHeight);
        for (const one of fish) {
          one.x *= scaleX;
          one.y *= scaleY;
        }
        if (count == null) return;
        while (fish.length > count && fish.length > MIN_SHOAL) {
          const going = fish.at(-1);
          if (going === attentive) attentive = null;
          for (const one of fish) if (one.mate === going) one.mate = null;
          fish.pop();
        }
        while (fish.length < count) fish.push(born());
        pair(fish);
      },
      step(seconds, pointer) {
        const dt = Math.min(Math.max(seconds, 0), 0.1);
        drift += DRIFT * dt;
        sank += DEPTH_DRIFT * dt;
        still = pointer && !pointer.moving ? still + dt : 0;
        const looking = still > LOOK_DELAY;
        const fleeing = (pointer == null ? void 0 : pointer.moving) === true;
        if (!looking || !pointer) {
          attentive = null;
          last = null;
          rest = 0;
          visit = 0;
        } else if (attentive) {
          visit += dt;
          const strayed = away(attentive, pointer) > LOOK_REACH * LOSE_INTEREST || away(attentive, pointer) > STANDOFF && !ahead(attentive, pointer);
          if (visit > LOOK_SPAN || strayed) {
            last = attentive;
            attentive = null;
            visit = 0;
            rest = LOOK_REST;
          }
        } else if (rest > 0) {
          rest -= dt;
        } else {
          attentive = nearest(fish, pointer, LOOK_REACH, last);
        }
        let arrived = false;
        for (let at = 0; at < fish.length; at++) {
          const one = fish[at];
          if (!one) continue;
          const sort = SPECIES[one.kind];
          one.hold -= dt;
          if (one.hold <= 0) decide(one, random, height, sort);
          one.lean = ease(one.lean, one.aim, BEND * dt);
          const startled = fleeing && pointer != null && away(one, pointer) < FLEE_REACH * PANIC;
          const [wantX, wantY] = want(
            one,
            fish,
            noise,
            drift,
            looking ? pointer : null,
            fleeing ? pointer : null,
            one === attentive,
            width,
            height
          );
          one.heading = toward(
            one.heading,
            steady(one.facing, Math.atan2(wantY, wantX), MAX_PITCH * sort.pitch),
            startled ? AGILITY_BOLT : AGILITY,
            startled ? TURN_STARTLED : TURN,
            dt
          );
          one.tilt = drawnTilt(one.heading, one.facing);
          const ambient = one.mate ? one.mate.depth : clamp(sort.deep + DEPTH_SWING * depths(one.lane, sank), DEPTH_FAR, DEPTH_NEAR);
          const wanted = startled ? ambient * DIVE : one === attentive ? RISE : ambient;
          one.depth = ease(one.depth, wanted, (startled ? DEPTH_DIVE : DEPTH_EASE) * dt);
          one.size = one.length * (1 - DEPTH_SIZE + DEPTH_SIZE * one.depth);
          const hovering = one === attentive && pointer && away(one, pointer) < STANDOFF;
          const gear = burst(one, sort, dt);
          const own = cruise * one.pace * one.size * gear;
          const wants = station(one, own) * (startled ? DART : hovering ? HOVER : 1);
          one.speed = ease(one.speed, wants, HASTE * dt);
          one.tail += 2 * Math.PI * one.speed / (STRIDE * sort.stride * one.size) * dt;
          const stroke = one.speed * (1 + SURGE * Math.cos(2 * one.tail));
          one.x += Math.cos(one.heading) * stroke * dt;
          one.y = clamp(one.y + Math.sin(one.heading) * stroke * dt, -EDGE_HOLD, height + EDGE_HOLD);
          if (gone(one.x, width, one.size)) {
            renew(at);
            arrived = true;
          }
        }
        if (arrived) pair(fish, JOIN_REACH, false);
      }
    };
  }
  function want(one, shoal, noise, drift, looking, fleeing, attentive, width, height) {
    const scale = FIELD_CELLS / width;
    const nx = one.x * scale + drift * 0.3;
    const ny = one.y * scale + drift;
    const pitched = one.lean + noise(nx + one.lane, ny + one.lane) * WOBBLE;
    let x = one.facing * Math.cos(pitched);
    let y = Math.sin(pitched);
    const reach2 = height * EDGE_REACH;
    y += edge(one.y, reach2) - edge(height - one.y, reach2);
    if (one.mate) {
      const spot = {
        moving: false,
        x: one.mate.x - one.mate.facing * one.mate.size * STATION_BACK,
        y: one.mate.y + one.mate.size * STATION_SIDE
      };
      const [awayX, awayY, distance] = separation(one, spot);
      x -= awayX / Math.max(distance, 0.5) * STATION_PUSH;
      y -= awayY / Math.max(distance, 0.5) * STATION_PUSH;
    }
    for (const other of shoal) {
      if (other === one || other === one.mate || other.mate === one) continue;
      const [awayX, awayY, distance] = separation(one, other);
      if (distance >= NEIGHBOUR_REACH) continue;
      const t = 1 - distance / NEIGHBOUR_REACH;
      const push = t * t * (3 - 2 * t) * NEIGHBOUR_PUSH / Math.max(distance, 0.5);
      x += awayX * push;
      y += awayY * push;
    }
    if (fleeing) {
      const [awayX, awayY, distance] = separation(one, fleeing);
      if (distance < FLEE_REACH) {
        const push = (FLEE_REACH - distance) / FLEE_REACH * FLEE_PUSH / Math.max(distance, 0.5);
        x += awayX * push;
        y += awayY * push;
      }
    }
    if (looking) {
      const [awayX, awayY, distance] = separation(one, looking);
      const push = attentive ? LOOK_PUSH : distance < LOOK_REACH ? LEAN_PUSH : 0;
      if (push > 0) {
        x -= awayX / Math.max(distance, 0.5) * push;
        y -= awayY / Math.max(distance, 0.5) * push;
      }
    }
    return [x, y];
  }
  function weigh(shares) {
    var _a;
    const wanted = shares != null ? shares : { cruiser: 1 };
    const run = [];
    let total = 0;
    for (const kind of ["cruiser", "darter", "drifter", "escort", "swordfish"]) {
      const share = Math.max(0, (_a = wanted[kind]) != null ? _a : 0);
      if (share <= 0) continue;
      total += share;
      run.push([kind, total]);
    }
    if (run.length === 0) return [["cruiser", 1]];
    return run.map(([kind, upto]) => [kind, upto / total]);
  }
  function draw(mix2, random) {
    var _a, _b, _c, _d;
    if (mix2.length <= 1) return (_b = (_a = mix2[0]) == null ? void 0 : _a[0]) != null ? _b : "cruiser";
    const roll = random();
    return (_d = (_c = mix2.find(([, upto]) => roll < upto)) == null ? void 0 : _c[0]) != null ? _d : mix2[mix2.length - 1][0];
  }
  function pair(shoal, reach2 = Number.POSITIVE_INFINITY, place2 = true) {
    const spare = shoal.filter((one) => one.kind === "escort" && !one.mate);
    for (const one of spare) {
      if (one.mate) continue;
      const led = shoal.some((other) => other.mate === one);
      if (led) continue;
      const leader = spare.find(
        (other) => other !== one && !other.mate && other.facing === one.facing && // Ahead of it, in its own direction of travel. A leader astern is a
        // follower that has to hold back for the rest of the crossing, and the
        // station rule will not let it slow down that far.
        (other.x - one.x) * one.facing > 0 && Math.hypot(other.x - one.x, other.y - one.y) < one.size * reach2
      );
      if (!leader) continue;
      if (shoal.some((other) => other.mate === leader)) continue;
      one.mate = leader;
      if (!place2) continue;
      one.x = leader.x - leader.facing * leader.size * STATION_BACK;
      one.y = leader.y + leader.size * STATION_SIDE;
    }
  }
  function burst(one, sort, dt) {
    if (sort.verve <= 0) return 1;
    const rate = SPURT_SLOWEST + one.lane % 1 * (SPURT_FASTEST - SPURT_SLOWEST);
    one.spurt += dt * rate;
    if (one.spurt >= 1) one.spurt -= 1;
    const gear = one.spurt < SPURT_SHARE ? SPURT_PUSH : SPURT_COAST;
    return 1 + (gear - 1) * sort.verve;
  }
  function station(one, own) {
    if (!one.mate) return own;
    const behind = (one.mate.x - one.x) * one.facing;
    const slip = (behind - one.mate.size * STATION_BACK) / Math.max(one.mate.size, 1);
    return one.mate.speed * clamp(1 + slip * STATION_CATCH, STATION_SLOWEST, STATION_BRISKEST);
  }
  function spawn(random, kind, box) {
    const sort = SPECIES[kind];
    const facing = random() < 0.5 ? -1 : 1;
    const aim = (random() - 0.5) * SWEEP * sort.pitch;
    const depth = DEPTH_FAR + random() * (DEPTH_NEAR - DEPTH_FAR);
    const length = (box.shortest + random() * (box.longest - box.shortest)) * sort.girth;
    const pace = (SLOWEST + random() ** LEISURE * (FASTEST - SLOWEST)) * sort.pace;
    const size = length * (1 - DEPTH_SIZE + DEPTH_SIZE * depth);
    return {
      aim,
      depth,
      facing,
      heading: steady(facing, aim, MAX_PITCH * sort.pitch),
      hold: random() * (HOLD_LEAST + HOLD_SPAN) * sort.hold,
      kind,
      lane: random() * 200,
      lean: aim,
      length,
      mate: null,
      pace,
      size,
      speed: box.cruise * pace * size,
      // Only a kind that bursts spends a draw on where in the burst it starts,
      // for the reason `draw` gives: a shoal that asked for none of this has to
      // come out of the seeded stream exactly as it did before there was any.
      spurt: sort.verve > 0 ? random() : 0,
      tail: random() * Math.PI * 2,
      tilt: drawnTilt(steady(facing, aim, MAX_PITCH * sort.pitch), facing),
      x: random() * box.width,
      y: random() * box.height
    };
  }
  function nearest(shoal, to, reach2, over) {
    let closest = null;
    let best = reach2;
    let spare = null;
    for (const one of shoal) {
      const distance = away(one, to);
      if (distance >= best || !ahead(one, to)) continue;
      if (one === over) {
        spare = one;
        continue;
      }
      best = distance;
      closest = one;
    }
    return closest != null ? closest : spare;
  }
  function ahead(one, to) {
    return (to.x - one.x) * Math.cos(one.heading) + (to.y - one.y) * Math.sin(one.heading) > 0;
  }
  var away = (one, to) => Math.hypot(one.x - to.x, one.y - to.y);
  function separation(one, to) {
    const x = one.x - to.x;
    const y = one.y - to.y;
    return [x, y, Math.hypot(x, y)];
  }
  function decide(one, random, height, sort) {
    const roll = random() * 2 - 1;
    const homing = -((one.y / Math.max(height, 1) - 0.5) * 2) * HOMING;
    const most = MAX_PITCH * sort.pitch;
    one.aim = clamp(homing + roll * Math.abs(roll) * SWEEP * sort.pitch, -most, most);
    one.hold = (HOLD_LEAST + random() * HOLD_SPAN) * sort.hold;
  }
  function toward(from, to, gain, most, dt) {
    let by = (to - from) % (Math.PI * 2);
    if (by > Math.PI) by -= Math.PI * 2;
    if (by < -Math.PI) by += Math.PI * 2;
    const rate = Math.max(-most, Math.min(most, by * gain));
    return from + rate * dt;
  }
  var AGILITY = 1.5;
  var AGILITY_BOLT = 4.2;
  function drawnTilt(heading, facing) {
    return Math.asin(clamp(Math.sin(heading), -1, 1)) * facing;
  }
  function steady(facing, want2, pitch) {
    const asked = Math.atan2(Math.sin(want2), facing * Math.cos(want2));
    const rel = pitch * Math.tanh(asked / pitch);
    return facing > 0 ? rel : Math.PI - rel;
  }
  var ease = (from, to, rate) => from + (to - from) * Math.min(1, Math.max(0, rate));
  function edge(distance, reach2) {
    if (reach2 <= 0 || distance >= reach2) return 0;
    return (reach2 - distance) / reach2 * EDGE_PUSH;
  }
  var clamp = (value, low, high) => Math.min(Math.max(value, low), high);
  function gone(x, span, body) {
    const margin = body * MARGIN;
    return x > span + margin || x < -margin;
  }
  var EDGE_HOLD = 8;

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/cephalopods.ts
  var CYCLE_SLOWEST = 3.4;
  var CYCLE_FASTEST = 6.8;
  var JET_SHARE = 0.16;
  var JET_PEAK = 4.2;
  var GLIDE = 0.07;
  var DRAG = 2.1;
  var SQUID_SHORTEST = 46;
  var SQUID_LONGEST = 78;
  var SQUID_PITCH = 0.42;
  var WANDER = 0.5;
  var RETHINK_LEAST = 2.5;
  var RETHINK_SPAN = 5;
  var ROOF = 0.72;
  var MARGIN2 = 1.1;
  var SHY_BAND = 2.4;
  var SHY_PULL = 1.4;
  var OCTOPUS_SMALLEST = 26;
  var OCTOPUS_LARGEST = 44;
  var CRAWL_REACH = 0.62;
  var CRAWL_RISE = 0.06;
  var GAIT = 0.55;
  var JET_ODDS = 8e-3;
  var JET_SPAN = 1.9;
  var JET_RUSH = 5.4;
  var JET_HEIGHT = 2.2;
  var TRAIL_HELD = 0.22;
  var TRAIL_DRIVEN = 1.15;
  var DEPTH_FAR2 = 0.15;
  var DEPTH_NEAR2 = 0.85;
  var DEPTH_SIZE2 = 0.6;
  var MIN_SPAN = 1;
  function createCephalopods(options) {
    const random = makeRandom(options.seed ^ 3184);
    let width = Math.max(MIN_SPAN, options.width);
    let height = Math.max(MIN_SPAN, options.height);
    let floor = options.floor;
    const squids = [];
    const octopuses = [];
    const beats = [];
    function bornSquid() {
      const depth = DEPTH_FAR2 + random() * (DEPTH_NEAR2 - DEPTH_FAR2);
      const facing = random() < 0.5 ? -1 : 1;
      const length = SQUID_SHORTEST + random() * (SQUID_LONGEST - SQUID_SHORTEST);
      const aim = (random() - 0.5) * WANDER;
      const x = random() * width;
      const size = length * (1 - DEPTH_SIZE2 + DEPTH_SIZE2 * depth);
      const top = size * MARGIN2;
      const bed = Math.max(top, Math.min(floor(x) - size * 0.4, height * ROOF));
      beats.push({
        aim,
        at: random() * CYCLE_SLOWEST,
        hold: RETHINK_LEAST + random() * RETHINK_SPAN,
        span: CYCLE_SLOWEST + random() * (CYCLE_FASTEST - CYCLE_SLOWEST)
      });
      return {
        depth,
        facing,
        heading: point(facing, aim),
        size,
        speed: 0,
        squeeze: 0,
        tilt: drawnTilt(point(facing, aim), facing),
        x,
        y: top + random() * (bed - top)
      };
    }
    function bornOctopus() {
      const depth = DEPTH_FAR2 + random() * (DEPTH_NEAR2 - DEPTH_FAR2);
      const head = OCTOPUS_SMALLEST + random() * (OCTOPUS_LARGEST - OCTOPUS_SMALLEST);
      const x = random() * width;
      return {
        crawl: random() * Math.PI * 2,
        depth,
        facing: random() < 0.5 ? -1 : 1,
        haul: 0,
        jetting: 0,
        lift: 0,
        size: head * (1 - DEPTH_SIZE2 + DEPTH_SIZE2 * depth),
        x,
        y: floor(x)
      };
    }
    function stock() {
      var _a, _b;
      squids.length = 0;
      octopuses.length = 0;
      beats.length = 0;
      for (let made = 0; made < Math.max(0, (_a = options.squids) != null ? _a : 0); made++) squids.push(bornSquid());
      for (let made = 0; made < Math.max(0, (_b = options.octopuses) != null ? _b : 0); made++) {
        octopuses.push(bornOctopus());
      }
    }
    stock();
    return {
      octopuses,
      resize(nextWidth, nextHeight, nextFloor) {
        const scaleX = Math.max(MIN_SPAN, nextWidth) / width;
        const scaleY = Math.max(MIN_SPAN, nextHeight) / height;
        width = Math.max(MIN_SPAN, nextWidth);
        height = Math.max(MIN_SPAN, nextHeight);
        floor = nextFloor;
        for (const one of squids) {
          one.x *= scaleX;
          one.y *= scaleY;
        }
        for (const one of octopuses) {
          one.x *= scaleX;
          one.y = floor(one.x);
        }
      },
      squids,
      step(seconds) {
        const dt = Math.min(Math.max(seconds, 0), 0.1);
        for (let at = 0; at < squids.length; at++) {
          const one = squids[at];
          const beat = beats[at];
          if (!one || !beat) continue;
          beat.at += dt;
          if (beat.at >= beat.span) {
            beat.at -= beat.span;
            beat.span = CYCLE_SLOWEST + random() * (CYCLE_FASTEST - CYCLE_SLOWEST);
          }
          const through = beat.at / beat.span;
          one.squeeze = through < JET_SHARE ? Math.sin(through / JET_SHARE * Math.PI) : 0;
          const push = one.squeeze * JET_PEAK * one.size;
          const glide = GLIDE * JET_PEAK * one.size;
          one.speed = push > one.speed ? push : glide + (one.speed - glide) * Math.max(0, 1 - DRAG * dt);
          beat.hold -= dt;
          if (beat.hold <= 0) {
            beat.aim = (random() - 0.5) * WANDER;
            beat.hold = RETHINK_LEAST + random() * RETHINK_SPAN;
          }
          const edge2 = one.size * MARGIN2;
          const bed = floor(one.x) - one.size * 0.4;
          one.heading = ease2(
            one.heading,
            point(one.facing, beat.aim + shy(one.y, edge2, bed, one.size)),
            TURN2 * dt
          );
          one.tilt = drawnTilt(one.heading, one.facing);
          one.x += Math.cos(one.heading) * one.speed * dt;
          one.y += Math.sin(one.heading) * one.speed * dt;
          if (one.x > width + edge2) one.x = -edge2;
          if (one.x < -edge2) one.x = width + edge2;
          one.y = Math.min(Math.max(one.y, edge2), bed);
        }
        for (const one of octopuses) {
          if (one.jetting > 0) {
            one.jetting = Math.max(0, one.jetting - dt);
            const through = 1 - one.jetting / JET_SPAN;
            one.haul = Math.sin(through * Math.PI) ** 0.6;
            one.lift = Math.sin(through * Math.PI) * JET_HEIGHT;
            one.x += one.facing * JET_RUSH * one.size * one.haul * dt;
          } else {
            one.crawl += GAIT * dt * Math.PI * 2;
            const pull = Math.max(0, Math.sin(one.crawl));
            one.haul = pull ** 1.4;
            one.lift = one.haul * CRAWL_RISE;
            one.x += one.facing * CRAWL_REACH * one.haul * one.size * dt;
            if (random() < JET_ODDS) one.jetting = JET_SPAN;
          }
          const edge2 = one.size * MARGIN2;
          if (one.x > width + edge2) one.x = -edge2;
          if (one.x < -edge2) one.x = width + edge2;
          one.y = floor(one.x) - one.lift * one.size;
        }
      }
    };
  }
  function shy(y, top, bed, size) {
    const band = Math.max(1, Math.min(size * SHY_BAND, (bed - top) * 0.4));
    const under = Math.max(0, top + band - y);
    const over = Math.max(0, y - (bed - band));
    return (under - over) / band * SHY_PULL;
  }
  var TURN2 = 0.9;
  function ease2(from, to, step) {
    const gap = to - from;
    return Math.abs(gap) <= step ? to : from + Math.sign(gap) * step;
  }
  function point(facing, want2) {
    const asked = Math.atan2(Math.sin(want2), facing * Math.cos(want2));
    const rel = SQUID_PITCH * Math.tanh(asked / SQUID_PITCH);
    return facing > 0 ? rel : Math.PI - rel;
  }
  function squidBody(squeeze) {
    const fat = 0.19 - squeeze * 0.07;
    const long = 0.62 + squeeze * 0.1;
    const fin2 = 0.2 - squeeze * 0.05;
    return [
      `M${long.toFixed(3)} 0`,
      `Q${(long * 0.55).toFixed(3)} ${(-fat).toFixed(3)} 0 ${(-fat * 0.72).toFixed(3)}`,
      `L0 ${(fat * 0.72).toFixed(3)}`,
      `Q${(long * 0.55).toFixed(3)} ${fat.toFixed(3)} ${long.toFixed(3)} 0`,
      "Z",
      // The fins, one either side, back where the mantle is widest.
      `M${(long * 0.52).toFixed(3)} ${(-fat * 0.86).toFixed(3)}`,
      `Q${(long * 0.86).toFixed(3)} ${(-fat - fin2).toFixed(3)} ${(long * 0.97).toFixed(3)} ${(-fat * 0.2).toFixed(3)}`,
      "Z",
      `M${(long * 0.52).toFixed(3)} ${(fat * 0.86).toFixed(3)}`,
      `Q${(long * 0.86).toFixed(3)} ${(fat + fin2).toFixed(3)} ${(long * 0.97).toFixed(3)} ${(fat * 0.2).toFixed(3)}`,
      "Z"
    ].join(" ");
  }
  function squidArms(squeeze, count = 8) {
    const arms = [];
    const spread = (1 - squeeze) * 0.44 + 0.2;
    for (let made = 0; made < count; made++) {
      const side = made / (count - 1) - 0.5;
      const lean = side * spread;
      const reach2 = 0.34 + Math.abs(side) * 0.16;
      const points = [];
      for (let step = 0; step <= 5; step++) {
        const t = step / 5;
        points.push({
          x: -t * reach2,
          y: lean * t * (0.5 + t) + Math.sin(t * 2.6 + side * 5) * 0.03 * (1 - squeeze) * t
        });
      }
      arms.push(points);
    }
    return arms;
  }
  var OCTOPUS_HEAD = "M-0.3 0.14 Q-0.5 -0.06 -0.44 -0.4 Q-0.36 -0.78 0 -0.8 Q0.36 -0.78 0.44 -0.4 Q0.5 -0.06 0.3 0.14 Z";
  function octopusArms(crawl, facing, haul = 0, count = 8) {
    const arms = [];
    const drive = Math.min(Math.max(haul, 0), 1);
    for (let made = 0; made < count; made++) {
      const side = made / (count - 1) - 0.5;
      const phase = crawl + (side > 0 ? 0 : Math.PI) + made * 0.12;
      const work = Math.sin(phase);
      const reach2 = (0.9 + Math.abs(side) * 0.5) * (0.88 + work * 0.12);
      const stream = -facing * (TRAIL_HELD + drive * TRAIL_DRIVEN);
      const fan = 2.5 * (1 - drive * 0.62);
      const points = [];
      for (let step = 0; step <= 6; step++) {
        const t = step / 6;
        const along2 = side * fan * reach2 * t;
        const wave2 = Math.sin(phase + t * 2.2) * 0.14 * t * (1 - t) * 4;
        points.push({
          x: along2 + stream * t * reach2,
          y: (t * t * 0.34 + t * 0.1) * (1 - drive * 0.7) - wave2 * 0.22
        });
      }
      arms.push(points);
    }
    return arms;
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/drift.ts
  var FIELD_CELLS2 = 2.2;
  var DRIFT2 = 0.04;
  var SWAY = 13;
  var FALL_SLOWEST = 4;
  var FALL_FASTEST = 13;
  var MOTE_SMALLEST = 0.4;
  var MOTE_LARGEST = 1.9;
  var MOTE_BIAS = 2.6;
  var DEPTH_SIZE3 = 0.75;
  var DEPTH_NEAR3 = 1;
  var DEPTH_FAR3 = 0.08;
  var RISE_SLOWEST = 38;
  var RISE_FASTEST = 66;
  var BUBBLE_SMALLEST = 1.1;
  var BUBBLE_LARGEST = 2.9;
  var SWELL = 0.6;
  var WOBBLE2 = 9;
  var WOBBLE_RATE = 1.9;
  var VENT_RUN_LEAST = 0.7;
  var VENT_RUN_SPAN = 1.6;
  var VENT_REST_LEAST = 5;
  var VENT_REST_SPAN = 14;
  var VENT_GAP_LEAST = 0.07;
  var VENT_GAP_SPAN = 0.5;
  var MIN_SPAN2 = 1;
  function createDrift(options) {
    var _a, _b;
    const noise = makeNoise2(options.seed ^ 7487);
    const random = makeRandom(options.seed ^ 31265);
    let width = Math.max(MIN_SPAN2, options.width);
    let height = Math.max(MIN_SPAN2, options.height);
    let slide = 0;
    const floor = (_a = options.floor) != null ? _a : (() => height);
    const mote = () => {
      const depth = DEPTH_FAR3 + random() * (DEPTH_NEAR3 - DEPTH_FAR3);
      const shrink = 1 - DEPTH_SIZE3 + DEPTH_SIZE3 * depth;
      return {
        depth,
        lane: random() * 200,
        r: (MOTE_SMALLEST + random() ** MOTE_BIAS * (MOTE_LARGEST - MOTE_SMALLEST)) * shrink,
        rate: (FALL_SLOWEST + random() * (FALL_FASTEST - FALL_SLOWEST)) * shrink,
        x: random() * width,
        y: random() * height
      };
    };
    const motes = Array.from({ length: Math.max(0, options.motes) }, mote);
    const vent = () => {
      const x = random() * width;
      return {
        next: 0,
        running: false,
        until: random() * (VENT_REST_LEAST + VENT_REST_SPAN),
        x,
        y: floor(x)
      };
    };
    const vents = Array.from({ length: Math.max(0, (_b = options.vents) != null ? _b : 0) }, vent);
    const bubbles = [];
    function release(from) {
      const depth = DEPTH_FAR3 + random() * (DEPTH_NEAR3 - DEPTH_FAR3);
      bubbles.push({
        depth,
        lane: random() * 200,
        r: (BUBBLE_SMALLEST + random() * (BUBBLE_LARGEST - BUBBLE_SMALLEST)) * depth,
        rose: 0,
        x: from.x + (random() - 0.5) * WOBBLE2,
        y: from.y
      });
    }
    return {
      bubbles,
      motes,
      resize(nextWidth, nextHeight, count) {
        const scaleX = Math.max(MIN_SPAN2, nextWidth) / width;
        const scaleY = Math.max(MIN_SPAN2, nextHeight) / height;
        width = Math.max(MIN_SPAN2, nextWidth);
        height = Math.max(MIN_SPAN2, nextHeight);
        for (const one of motes) {
          one.x *= scaleX;
          one.y *= scaleY;
        }
        for (const one of bubbles) {
          one.x *= scaleX;
          one.y *= scaleY;
        }
        if (count == null) return;
        while (motes.length > count) motes.pop();
        while (motes.length < count) motes.push(mote());
      },
      step(seconds) {
        const dt = Math.min(Math.max(seconds, 0), 0.1);
        slide += DRIFT2 * dt;
        const scale = FIELD_CELLS2 / width;
        for (const one of motes) {
          const push = noise(one.x * scale + one.lane, one.y * scale + one.lane + slide);
          one.x += push * SWAY * one.depth * dt;
          one.y += one.rate * dt;
          if (one.y > height + one.r) {
            one.y = -one.r;
            one.x = random() * width;
          }
          one.x = around(one.x, width, one.r);
        }
        for (const from of vents) {
          from.until -= dt;
          if (from.until <= 0) {
            from.running = !from.running;
            from.until = from.running ? VENT_RUN_LEAST + random() * VENT_RUN_SPAN : VENT_REST_LEAST + random() * VENT_REST_SPAN;
            from.next = 0;
          }
          if (!from.running) continue;
          from.next -= dt;
          if (from.next > 0) continue;
          from.next = VENT_GAP_LEAST + random() * VENT_GAP_SPAN;
          release(from);
        }
        for (let at = bubbles.length - 1; at >= 0; at--) {
          const one = bubbles[at];
          if (!one) continue;
          const climb = (RISE_SLOWEST + one.depth * (RISE_FASTEST - RISE_SLOWEST)) * one.depth;
          one.rose += dt;
          one.y -= climb * dt;
          one.r += one.r * SWELL * (climb / Math.max(height, MIN_SPAN2)) * dt;
          one.x += Math.cos(one.rose * WOBBLE_RATE + one.lane) * WOBBLE2 * dt;
          if (one.y + one.r < 0) bubbles.splice(at, 1);
        }
      }
    };
  }
  function around(value, span, margin) {
    if (value > span + margin) return -margin;
    if (value < -margin) return span + margin;
    return value;
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/fish_shape.ts
  var SPAN = 38;
  var NOSE = 29;
  var along = (t) => 21 * t * (1 - t) ** 2 + 63 * t ** 2 * (1 - t) + 29 * t ** 3;
  var half = (t) => 24 * t * (1 - t) + WRIST * (1 - t);
  var WRIST = 1.4;
  var STATIONS = 20;
  var SWEEP2 = 0.2;
  var WAVES = 0.85;
  var TWIST = 2 * Math.PI * WAVES;
  var envelope = (u) => 0.2 - 0.8 * u + 1.6 * u * u;
  var wave = (u, phase) => envelope(u) * Math.sin(TWIST * u - phase);
  var SLOPE = 0.6;
  var FLUKE_BACK = -9;
  var FLUKE_SPREAD = 7;
  var FLUKE_NOTCH = -7;
  var SAMPLES = 90;
  function reach(amp) {
    let low = Number.POSITIVE_INFINITY;
    let high = Number.NEGATIVE_INFINITY;
    for (let at = 0; at < SAMPLES; at++) {
      const phase = at / SAMPLES * 2 * Math.PI;
      const sway = (x) => amp * wave(1 - x / NOSE, phase);
      const angle = Math.atan2(sway(SLOPE) - sway(-SLOPE), 2 * SLOPE);
      const tip = sway(0) + FLUKE_BACK * Math.sin(angle);
      low = Math.min(low, tip);
      high = Math.max(high, tip);
    }
    return high - low;
  }
  function fitted() {
    let amp = SWEEP2 * SPAN;
    for (let pass = 0; pass < 8; pass++) amp *= SWEEP2 * SPAN / reach(amp);
    return amp;
  }
  var AMP = fitted();
  function spine(x, phase) {
    return AMP * wave(1 - x / NOSE, phase);
  }
  function station2(x, phase) {
    const back = spine(x - SLOPE, phase);
    const front = spine(x + SLOPE, phase);
    return { angle: Math.atan2(front - back, 2 * SLOPE), x, y: spine(x, phase) };
  }
  var clear = (on, lift) => [
    on.x + Math.sin(on.angle) * lift,
    on.y - Math.cos(on.angle) * lift
  ];
  var above = (x, lift, phase) => clear(station2(x, phase), lift);
  var fixed = (value) => value.toFixed(2);
  function rounded(points) {
    const mid = (a, b) => `${fixed((a[0] + b[0]) / 2)} ${fixed((a[1] + b[1]) / 2)}`;
    const last = points[points.length - 1];
    let d = `M${mid(last, points[0])}`;
    for (let at = 0; at < points.length; at++) {
      const here = points[at];
      const next = points[(at + 1) % points.length];
      d += `Q${fixed(here[0])} ${fixed(here[1])} ${mid(here, next)}`;
    }
    return `${d}Z`;
  }
  var fin = (points) => `M${points.map(([x, y]) => `${fixed(x)} ${fixed(y)}`).join("L")}Z`;
  function dorsal(phase) {
    const foot = (t, over) => {
      const x = along(t);
      return clear(station2(x, phase), half(t) + over);
    };
    return fin([foot(0.38, -SET), foot(0.52, TIP), foot(0.66, -SET)]);
  }
  var SET = 0.8;
  var TIP = 5;
  function outline(phase) {
    const top = [];
    const bottom = [];
    for (let at = 0; at <= STATIONS; at++) {
      const t = at / STATIONS;
      const x = along(t);
      const on = station2(x, phase);
      const lift = half(t);
      top.push(clear(on, lift));
      bottom.push(clear(on, -lift));
    }
    return [...top, ...bottom.reverse()];
  }
  var ROOT = 2.5;
  function tail(phase) {
    const joint = station2(0, phase);
    const cos = Math.cos(joint.angle);
    const sin = Math.sin(joint.angle);
    const carry = ([x, y]) => [
      joint.x + x * cos - y * sin,
      joint.y + x * sin + y * cos
    ];
    return fin([
      carry([ROOT, 0]),
      carry([FLUKE_BACK, FLUKE_SPREAD]),
      carry([FLUKE_NOTCH, 0]),
      carry([FLUKE_BACK, -FLUKE_SPREAD])
    ]);
  }
  var STEPS = 48;
  var drawn = new Array(STEPS);
  var EYE_R = 1.5;
  var EYE_X = 22;
  var EYE_LIFT = 2;
  function build(at) {
    const phase = at / STEPS * 2 * Math.PI;
    const [x, y] = above(EYE_X, EYE_LIFT, phase);
    const d = rounded(outline(phase)) + tail(phase) + dorsal(phase);
    return {
      at,
      billed: d + bill(phase),
      d,
      eye: { r: EYE_R, x, y }
    };
  }
  function bill(phase) {
    const nose = station2(NOSE, phase);
    const cos = Math.cos(nose.angle);
    const sin = Math.sin(nose.angle);
    const carry = ([x, y]) => [
      nose.x + x * cos - y * sin,
      nose.y + x * sin + y * cos
    ];
    return fin([
      carry([-BILL_ROOT, -BILL_GIRTH]),
      carry([BILL_REACH, 0]),
      carry([-BILL_ROOT, BILL_GIRTH])
    ]);
  }
  var BILL_REACH = 15;
  var BILL_GIRTH = 1.1;
  var BILL_ROOT = 3;
  function frameAt(phase) {
    const at = (Math.round(phase / (2 * Math.PI) * STEPS) % STEPS + STEPS) % STEPS;
    const had = drawn[at];
    if (had) return had;
    const made = build(at);
    drawn[at] = made;
    return made;
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/flora.ts
  var CORAL = [
    { d: "M0 0 C-2 -14 -10 -18 -16 -26", width: 5 },
    { d: "M0 0 C0 -16 2 -24 0 -34", width: 6 },
    { d: "M0 0 C2 -12 10 -16 18 -22", width: 4.5 },
    { d: "M-8 -14 C-12 -20 -16 -22 -22 -24", width: 3 },
    { d: "M8 -12 C12 -18 18 -20 24 -20", width: 3 }
  ];
  var BUSH = [
    { d: "M0 0 C-4 -8 -14 -10 -24 -12", width: 4 },
    { d: "M0 0 C-2 -10 -6 -15 -10 -22", width: 4.5 },
    { d: "M0 0 C1 -9 3 -14 4 -20", width: 5 },
    { d: "M0 0 C4 -8 12 -11 22 -14", width: 4 },
    { d: "M-12 -9 C-16 -14 -18 -16 -20 -22", width: 2.5 },
    { d: "M10 -10 C14 -14 18 -15 22 -20", width: 2.5 }
  ];
  var STAGHORN = [
    { d: "M0 0 C0 -12 -2 -22 -6 -34", width: 5.5 },
    { d: "M0 0 C3 -10 6 -18 8 -30", width: 4.5 },
    { d: "M-3 -20 C-8 -26 -12 -28 -16 -36", width: 3 },
    { d: "M6 -20 C10 -26 14 -27 18 -32", width: 3 },
    { d: "M0 -6 C-6 -10 -10 -12 -14 -14", width: 2.5 }
  ];
  var BOULDER = [
    { d: "M0 0 C-9 -4 -13 -9 -12 -15", width: 7 },
    { d: "M0 0 C-4 -6 -5 -12 -4 -18", width: 7 },
    { d: "M0 0 C3 -6 5 -12 5 -17", width: 7 },
    { d: "M0 0 C9 -4 13 -9 11 -15", width: 7 }
  ];
  var REEF = [BOULDER, BOULDER, BUSH, BUSH, CORAL, STAGHORN];
  var FIELD_CELLS3 = 3.6;
  var DRIFT3 = 0.06;
  var KELP_LEAST = 0.22;
  var KELP_SPAN = 0.3;
  var GRASS_LEAST = 0.05;
  var GRASS_SPAN = 0.085;
  var TUFT_LEAST = 3;
  var TUFT_MOST = 7;
  var TUFT_SPLAY = 0.34;
  var TUFT_ROOT = 0.16;
  var GRASS_RUNT = 0.5;
  var KELP_GIRTH = 5.2;
  var GRASS_GIRTH = 2;
  var KELP_STEPS = 12;
  var GRASS_STEPS = 6;
  var KELP_LEAN = 0.34;
  var GRASS_LEAN = 0.14;
  var SWAY_SLOWEST = 0.22;
  var SWAY_FASTEST = 0.44;
  var CURRENT_SHARE = 0.68;
  var BLADES = 7;
  var BLADE_SEAT = 0.14;
  var BLADE_STEPS = 4;
  var BLADE_SPAN = 0.44;
  var BLADE_TRAIL = 0.95;
  var BLADE_FLARE = 0.3;
  var BLADE_TAPER = 0.45;
  var CORAL_SMALLEST = 0.9;
  var CORAL_LARGEST = 2.4;
  var DEPTH_FAR4 = 0.22;
  var DEPTH_NEAR4 = 1;
  var MIN_SPAN3 = 1;
  function createFlora(options) {
    const noise = makeNoise2(options.seed ^ 20240);
    const random = makeRandom(options.seed ^ 27452);
    let width = Math.max(MIN_SPAN3, options.width);
    let height = Math.max(MIN_SPAN3, options.height);
    let floor = options.floor;
    let drift = 0;
    const plants = [];
    const sways = [];
    const heights = /* @__PURE__ */ new Map();
    function plant(kind) {
      var _a;
      const x = random() * width;
      const depth = DEPTH_FAR4 + random() * (DEPTH_NEAR4 - DEPTH_FAR4);
      if (kind === "coral") {
        plants.push({
          blades: [],
          depth,
          girth: 0,
          kind,
          points: [],
          scale: (CORAL_SMALLEST + random() * (CORAL_LARGEST - CORAL_SMALLEST)) * depth,
          twigs: (_a = REEF[Math.floor(random() * REEF.length)]) != null ? _a : CORAL,
          x,
          y: floor(x, depth)
        });
        sways.push({ lean: 0, mates: [], own: random() * Math.PI * 2, rate: 0, steps: 0 });
        return;
      }
      const tall = kind === "kelp";
      const span = height * (tall ? KELP_LEAST + random() * KELP_SPAN : GRASS_LEAST + random() * GRASS_SPAN) * depth;
      plants.push({
        blades: [],
        depth,
        girth: (tall ? KELP_GIRTH : GRASS_GIRTH) * depth,
        kind,
        points: [],
        scale: 1,
        twigs: [],
        x,
        y: floor(x, depth)
      });
      sways.push({
        lean: span * (tall ? KELP_LEAN : GRASS_LEAN),
        mates: tall ? [] : clump(span),
        own: random() * Math.PI * 2,
        rate: SWAY_SLOWEST + random() * (SWAY_FASTEST - SWAY_SLOWEST),
        steps: tall ? KELP_STEPS : GRASS_STEPS
      });
      heights.set(plants.length - 1, span);
    }
    function clump(span) {
      const mates = [];
      const count = TUFT_LEAST + Math.floor(random() * (TUFT_MOST - TUFT_LEAST + 1));
      for (let made = 0; made < count; made++) {
        const side = made % 2 === 0 ? 1 : -1;
        const out = (Math.floor(made / 2) + 1) / Math.ceil(count / 2);
        mates.push({
          beat: 0.82 + random() * 0.4,
          own: random() * Math.PI * 2,
          shift: side * out * span * TUFT_ROOT * (0.4 + random() * 0.6),
          slant: side * out * TUFT_SPLAY * (0.5 + random() * 0.5),
          span: span * (GRASS_RUNT + random() * (1 - GRASS_RUNT))
        });
      }
      return mates;
    }
    function sow() {
      var _a, _b, _c;
      plants.length = 0;
      sways.length = 0;
      heights.clear();
      for (let made = 0; made < Math.max(0, (_a = options.kelps) != null ? _a : 0); made++) plant("kelp");
      for (let made = 0; made < Math.max(0, (_b = options.grasses) != null ? _b : 0); made++) plant("grass");
      for (let made = 0; made < Math.max(0, (_c = options.corals) != null ? _c : 0); made++) plant("coral");
    }
    function bend(at, field) {
      const one = plants[at];
      const sway = sways[at];
      const span = heights.get(at);
      if (!one || !sway || span == null || one.kind === "coral") return;
      const current = field(one.x / width * FIELD_CELLS3 + drift, drift);
      const own = Math.sin(sway.own);
      const amp = sway.lean * (current * CURRENT_SHARE + own * (1 - CURRENT_SHARE));
      const points = strand(one.x, one.y, span, sway.own, amp, 0, sway.steps);
      one.points = points;
      if (one.kind === "grass") {
        one.blades = sway.mates.map(
          (mate) => strand(
            one.x + mate.shift,
            one.y,
            mate.span,
            sway.own * mate.beat + mate.own,
            amp,
            mate.slant,
            sway.steps
          )
        );
        return;
      }
      const blades = [];
      for (let made = 0; made < BLADES; made++) {
        const seat = BLADE_SEAT + made / BLADES * (1 - BLADE_SEAT);
        const at2 = Math.round(seat * sway.steps);
        const on = points[Math.min(points.length - 1, at2)];
        const under = points[Math.max(0, at2 - 1)];
        if (!on || !under) continue;
        const runX = on.x - under.x;
        const runY = on.y - under.y;
        const run = Math.hypot(runX, runY) || 1;
        const side = made % 2 === 0 ? 1 : -1;
        const reach2 = span * BLADE_SPAN * (1 - BLADE_TAPER * seat);
        const trailX = -runX / run;
        const trailY = -runY / run;
        const flareX = -runY / run * side;
        const flareY = runX / run * side;
        const blade = [];
        for (let step = 0; step <= BLADE_STEPS; step++) {
          const u = step / BLADE_STEPS;
          const out = Math.sin(u * Math.PI * 0.62) * (1 - u * 0.72) * BLADE_FLARE;
          const down = u * BLADE_TRAIL;
          blade.push({
            x: on.x + (trailX * down + flareX * out) * reach2,
            y: on.y + (trailY * down + flareY * out) * reach2
          });
        }
        blades.push(blade);
      }
      one.blades = blades;
    }
    function strand(x, y, span, phase, amp, slant, steps) {
      const lean = Math.sin(slant);
      const rise = Math.cos(slant);
      const points = [];
      for (let step = 0; step <= steps; step++) {
        const t = step / steps;
        points.push({
          x: x + span * t * lean + amp * Math.sin(phase + t * 2.4) * t,
          y: y - span * t * rise
        });
      }
      return points;
    }
    function carry(seconds) {
      drift += DRIFT3 * seconds;
      for (let at = 0; at < sways.length; at++) {
        const sway = sways[at];
        if (sway && sway.rate > 0) sways[at] = __spreadProps(__spreadValues({}, sway), { own: sway.own + sway.rate * seconds });
      }
    }
    function recut() {
      for (let at = 0; at < plants.length; at++) bend(at, noise);
    }
    function advance(seconds) {
      carry(Math.min(Math.max(seconds, 0), 0.1));
      recut();
    }
    sow();
    advance(0);
    return {
      plants,
      resize(nextWidth, nextHeight, nextFloor) {
        width = Math.max(MIN_SPAN3, nextWidth);
        height = Math.max(MIN_SPAN3, nextHeight);
        floor = nextFloor;
        sow();
        advance(0);
      },
      step: advance,
      wind(seconds) {
        carry(Math.max(seconds, 0));
        recut();
      }
    };
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/passers.ts
  var FADE = 0.16;
  var WATERLINE = 0.035;
  var OFFING = 0.2;
  var PING_EDGE = 0.18;
  var HABITS = {
    boat: {
      chance: 1,
      deepLeast: WATERLINE,
      deepSpan: 0,
      sizeLeast: 0.04,
      sizeSpan: 0.03,
      takeLeast: 26,
      takeSpan: 18
    },
    sonar: {
      chance: 1,
      deepLeast: 0.12,
      deepSpan: 0.43,
      sizeLeast: 0.4,
      sizeSpan: 0.3,
      takeLeast: 4.5,
      takeSpan: 2.5
    },
    submarine: {
      chance: 0.15,
      deepLeast: 0.17,
      deepSpan: 0.19,
      sizeLeast: 0.036,
      sizeSpan: 0.022,
      takeLeast: 38,
      takeSpan: 22
    }
  };
  var DAY = 24 * 60 * 60;
  var WAIT_LEAST = 35;
  var WAIT_SPAN = 130;
  var APART = 90;
  var MIN_SPAN4 = 1;
  function createPassers(options) {
    var _a, _b;
    const random = makeRandom(options.seed ^ 12471);
    const kinds = (_a = options.kinds) != null ? _a : ["boat", "sonar", "submarine"];
    const eager = (_b = options.eager) != null ? _b : false;
    let width = Math.max(MIN_SPAN4, options.width);
    let height = Math.max(MIN_SPAN4, options.height);
    const passing = [];
    const takes = /* @__PURE__ */ new Map();
    let planned = 0;
    const due = /* @__PURE__ */ new Map();
    const waits = /* @__PURE__ */ new Map();
    const gone2 = /* @__PURE__ */ new Set();
    let apart = APART;
    function plan(day) {
      planned = day;
      gone2.clear();
      const dice = makeRandom(stir(options.seed ^ day ^ 20973) | 0);
      for (const kind of kinds) {
        const happens = dice() < HABITS[kind].chance;
        const at = Math.floor(dice() * DAY);
        due.set(kind, happens ? at : null);
        waits.set(kind, WAIT_LEAST + dice() * WAIT_SPAN);
      }
    }
    function launch(kind) {
      const habit = HABITS[kind];
      const facing = random() < 0.5 ? -1 : 1;
      const scale = width * (habit.sizeLeast + random() * habit.sizeSpan);
      const deep = habit.deepLeast + random() * habit.deepSpan;
      takes.set(kind, habit.takeLeast + random() * habit.takeSpan);
      gone2.add(kind);
      const side = kind === "sonar" ? facing > 0 ? 1 - PING_EDGE : PING_EDGE : 0;
      passing.push({
        along: 0,
        facing,
        kind,
        scale,
        weight: 0,
        x: width * side,
        y: height * deep
      });
    }
    function owed(dt, clock) {
      var _a2;
      if (passing.length > 0 || apart > 0) return null;
      let next = null;
      let oldest = Number.POSITIVE_INFINITY;
      for (const kind of kinds) {
        if (gone2.has(kind)) continue;
        const at = due.get(kind);
        if (at == null || clock < at || at >= oldest) continue;
        oldest = at;
        next = kind;
      }
      if (!next) return null;
      const left = ((_a2 = waits.get(next)) != null ? _a2 : 0) - dt;
      waits.set(next, left);
      return left <= 0 ? next : null;
    }
    return {
      passing,
      resize(nextWidth, nextHeight) {
        width = Math.max(MIN_SPAN4, nextWidth);
        height = Math.max(MIN_SPAN4, nextHeight);
        passing.length = 0;
      },
      step(seconds, now = /* @__PURE__ */ new Date()) {
        var _a2, _b2;
        const dt = Math.min(Math.max(seconds, 0), 0.1);
        const day = now.getFullYear() * 1e4 + (now.getMonth() + 1) * 100 + now.getDate();
        if (day !== planned) plan(day);
        apart = Math.max(0, apart - dt);
        if (eager) {
          if (passing.length === 0) {
            gone2.clear();
            launch((_a2 = kinds[Math.floor(random() * kinds.length)]) != null ? _a2 : "boat");
          }
        } else {
          const next = owed(dt, now.getHours() * 3600 + now.getMinutes() * 60 + now.getSeconds());
          if (next) launch(next);
        }
        for (let at = passing.length - 1; at >= 0; at--) {
          const one = passing[at];
          if (!one) continue;
          one.along += dt / Math.max((_b2 = takes.get(one.kind)) != null ? _b2 : 1, 1e-3);
          if (one.along >= 1) {
            passing.splice(at, 1);
            apart = APART;
            continue;
          }
          one.weight = Math.min(1, one.along / FADE, (1 - one.along) / FADE);
          if (one.kind === "sonar") continue;
          const from = -OFFING * width;
          const to = width * (1 + OFFING);
          one.x = one.facing > 0 ? from + one.along * (to - from) : to - one.along * (to - from);
        }
      }
    };
  }
  var HULL = "M-1 0 L1 0 L0.82 0.2 Q0.1 0.34 -0.72 0.28 Q-0.94 0.24 -1 0 Z";
  var SCREWS = "M-0.78 0.15 A0.07 0.07 0 1 1 -0.78 0.29 A0.07 0.07 0 1 1 -0.78 0.15 Z M-0.62 0.19 A0.07 0.07 0 1 1 -0.62 0.33 A0.07 0.07 0 1 1 -0.62 0.19 Z";
  var WAKE = [
    { from: [-0.94, 0.12], to: [-2.6, -0.34] },
    { from: [-0.94, 0.22], to: [-2.6, 0.62] }
  ];
  var SUBMARINE = "M-0.92 -0.15 L0.4 -0.17 Q0.86 -0.16 1 0 Q0.86 0.16 0.4 0.17 L-0.92 0.15 Q-1 0.1 -1 0 Q-1 -0.1 -0.92 -0.15 Z M0.02 -0.16 L0.08 -0.44 L0.3 -0.44 L0.34 -0.16 Z M0.16 -0.44 L0.16 -0.62 L0.2 -0.62 L0.2 -0.44 Z M-0.02 -0.38 L0.42 -0.38 L0.42 -0.33 L-0.02 -0.33 Z M-0.74 -0.14 L-0.96 -0.4 L-0.84 -0.4 L-0.62 -0.14 Z M-0.62 0.14 L-0.84 0.4 L-0.96 0.4 L-0.74 0.14 Z";
  var SUB_SCREW = "M-1 -0.02 L-1.14 -0.14 L-1.18 -0.06 L-1.04 0 L-1.18 0.06 L-1.14 0.14 L-1 0.02 Z";
  var PING_RINGS = [0, 0.16, 0.32];
  function ringAt(along2, offset) {
    const t = (along2 - offset) / (1 - offset);
    if (t <= 0 || t >= 1) return null;
    return { reach: 1 - (1 - t) ** 2, weight: (1 - t) ** 1.6 };
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/rays.ts
  var SPREAD = 2.4;
  var SPAN_LEAST = 0.018;
  var SPAN_SPAN = 0.055;
  var REACH_LEAST = 0.45;
  var REACH_SPAN = 0.5;
  var TILT = 0.16;
  var TILT_SPREAD = 0.07;
  var GLOW_LEAST = 0.25;
  var GLOW_MOST = 1;
  var BREATH_SLOWEST = 0.045;
  var BREATH_FASTEST = 0.11;
  var WANDER2 = 26;
  var WANDER_RATE = 0.06;
  var MIN_SPAN5 = 1;
  function createRays(options) {
    const random = makeRandom(options.seed ^ 13239);
    let width = Math.max(MIN_SPAN5, options.width);
    let height = Math.max(MIN_SPAN5, options.height);
    let clock = 0;
    const breaths = [];
    const rays = [];
    function born() {
      breaths.push({
        at: random() * Math.PI * 2,
        rate: BREATH_SLOWEST + random() * (BREATH_FASTEST - BREATH_SLOWEST),
        seat: random() * Math.PI * 2
      });
      return {
        glow: GLOW_LEAST,
        reach: height * (REACH_LEAST + random() * REACH_SPAN),
        span: width * (SPAN_LEAST + random() * SPAN_SPAN),
        tilt: TILT + (random() - 0.5) * TILT_SPREAD,
        x: random() * width
      };
    }
    for (let made = 0; made < Math.max(0, options.count); made++) rays.push(born());
    return {
      rays,
      resize(nextWidth, nextHeight, count) {
        const scaleX = Math.max(MIN_SPAN5, nextWidth) / width;
        width = Math.max(MIN_SPAN5, nextWidth);
        height = Math.max(MIN_SPAN5, nextHeight);
        for (const one of rays) one.x *= scaleX;
        if (count == null) return;
        while (rays.length > count) {
          rays.pop();
          breaths.pop();
        }
        while (rays.length < count) rays.push(born());
      },
      step(seconds) {
        clock += Math.min(Math.max(seconds, 0), 0.1);
        for (let at = 0; at < rays.length; at++) {
          const one = rays[at];
          const breath = breaths[at];
          if (!one || !breath) continue;
          const swell = (Math.sin(breath.at + clock * breath.rate * Math.PI * 2) + 1) / 2;
          one.glow = GLOW_LEAST + swell * (GLOW_MOST - GLOW_LEAST);
          one.x += Math.cos(breath.seat + clock * WANDER_RATE * Math.PI * 2) * WANDER2 * seconds;
        }
      }
    };
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/relics.ts
  var ODDS = {
    block: 0.34,
    chest: 0.1,
    smoker: 0.5,
    wreck: 0.4
  };
  var SIZES = {
    block: [17, 26],
    chest: [20, 29],
    smoker: [38, 66],
    wreck: [95, 170]
  };
  var LEAN = {
    block: 0.6,
    chest: 0.12,
    smoker: 0.05,
    wreck: 0.16
  };
  var DEPTH_FAR5 = 0.35;
  var DEPTH_NEAR5 = 0.85;
  var DEPTH_SIZE4 = 0.45;
  var PUFF_GAP = 0.13;
  var PUFF_SLOWEST = 0.72;
  var PUFF_FASTEST = 1.28;
  var PUFF_LIFE = 8;
  var PUFF_RISE = 52;
  var PUFF_DRAG = 0.62;
  var PUFF_SWELL = 4.5;
  var PUFF_SWAY = 16;
  var FIELD_CELLS4 = 2.4;
  var FIELD_ROWS = 5.5;
  var MIN_SPAN6 = 1;
  var WARMUP = 12;
  function createRelics(options) {
    const random = makeRandom(options.seed ^ 15407);
    const shear = makeNoise2(options.seed ^ 42780);
    let width = Math.max(MIN_SPAN6, options.width);
    let height = Math.max(MIN_SPAN6, options.height);
    let floor = options.floor;
    let since = 0;
    let drift = 0;
    const relics = [];
    const plume = [];
    function place2() {
      const roll = makeRandom(options.seed ^ 36369);
      for (let spun = 0; spun < WARMUP; spun++) roll();
      relics.length = 0;
      for (const kind of ["wreck", "smoker", "block", "chest"]) {
        if (roll() >= ODDS[kind]) continue;
        const [least, most] = SIZES[kind];
        const depth = DEPTH_FAR5 + roll() * (DEPTH_NEAR5 - DEPTH_FAR5);
        const x = width * (0.12 + roll() * 0.76);
        relics.push({
          depth,
          kind,
          lean: (roll() - 0.5) * LEAN[kind] * 2,
          scale: (least + roll() * (most - least)) * (1 - DEPTH_SIZE4 + DEPTH_SIZE4 * depth),
          x,
          y: floor(x)
        });
      }
    }
    const smoker = () => relics.find((one) => one.kind === "smoker");
    place2();
    return {
      plume,
      relics,
      resize(nextWidth, nextHeight, nextFloor) {
        width = Math.max(MIN_SPAN6, nextWidth);
        height = Math.max(MIN_SPAN6, nextHeight);
        floor = nextFloor;
        plume.length = 0;
        place2();
      },
      step(seconds) {
        const dt = Math.min(Math.max(seconds, 0), 0.1);
        drift += dt * 0.05;
        const vent = smoker();
        if (vent) {
          since += dt;
          if (since >= PUFF_GAP) {
            since = 0;
            plume.push({
              age: 0,
              r: vent.scale * (0.07 + random() * 0.06),
              rise: PUFF_SLOWEST + random() * (PUFF_FASTEST - PUFF_SLOWEST),
              x: vent.x + (random() - 0.5) * vent.scale * 0.3,
              y: vent.y - vent.scale * SMOKER_LIP
            });
          }
        }
        for (let at = plume.length - 1; at >= 0; at--) {
          const puff = plume[at];
          if (!puff) continue;
          puff.age += dt / PUFF_LIFE;
          if (puff.age >= 1 || puff.y + puff.r < 0) {
            plume.splice(at, 1);
            continue;
          }
          const climb = PUFF_RISE * puff.rise * (1 - PUFF_DRAG * puff.age);
          puff.y -= climb * dt;
          puff.r += PUFF_SWELL * (0.55 + puff.age) * dt;
          puff.x += shear(puff.x / width * FIELD_CELLS4 + drift, puff.y / height * FIELD_ROWS + drift) * PUFF_SWAY * dt;
        }
      }
    };
  }
  var WRECK = "M-1 0 L-0.62 -0.2 L0.52 -0.24 Q0.86 -0.23 1 -0.06 L0.94 0.04 Q0.4 0.11 -0.3 0.09 Z M-0.62 -0.2 L-0.58 -0.34 L0.44 -0.37 L0.52 -0.24 Z M0.1 -0.36 L0.16 -0.92 L0.23 -0.36 Z M-0.3 -0.35 L-0.2 -0.76 L-0.16 -0.35 Z";
  var WRECK_SPAR = [
    { x: 0.02, y: -0.74 },
    { x: 0.3, y: -0.66 }
  ];
  var SMOKER = "M-0.5 0 L-0.3 -0.7 L-0.22 -1.5 L-0.16 -2.1 L-0.2 -2.42 L-0.02 -2.5 L0.06 -2.16 L0.14 -2.34 L0.16 -1.9 L0.24 -1.2 L0.42 0 Z";
  var SMOKER_LIP = 2.45;
  var BLOCK_CARD = "M-1 -0.73 L1 -0.73 L1 0.73 L-1 0.73 Z";
  var BLOCK_LINES = [
    "M-0.62 -0.45 L0.2 -0.45 L0.2 -0.29 L-0.62 -0.29 Z",
    "M-0.62 -0.08 L0.74 -0.08 L0.74 0.08 L-0.62 0.08 Z",
    "M-0.62 0.29 L-0.03 0.29 L-0.03 0.45 L-0.62 0.45 Z"
  ];
  var CHEST_BODY = "M-1 0 L-1 -0.62 Q-1 -1.12 0 -1.12 Q1 -1.12 1 -0.62 L1 0 Z";
  var CHEST_BANDS = ["M-1 -0.66 L1 -0.66 L1 -0.58 L-1 -0.58 Z"];
  var CHEST_LOCK = "M-0.13 -0.72 L0.13 -0.72 L0.13 -0.44 L-0.13 -0.44 Z";
  var LAPTOP_SCREEN = "M-0.44 -1.94 L0.3 -2.04 L0.38 -1.2 L-0.36 -1.1 Z";
  var LAPTOP_BASE = "M-0.42 -1.14 L0.46 -1.24 L0.56 -1.1 L-0.34 -1 Z";
  var LAPTOP_LINES = [
    "M-0.3 -1.82 L0.02 -1.86 L0.02 -1.78 L-0.3 -1.74 Z",
    "M-0.3 -1.66 L0.16 -1.72 L0.16 -1.64 L-0.3 -1.58 Z",
    "M-0.3 -1.5 L-0.08 -1.53 L-0.08 -1.45 L-0.3 -1.42 Z"
  ];

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/seabed.ts
  var FLOOR_SEAT = 0.1;
  var FLOOR_ROLL = 0.085;
  var HORIZON_SEAT = 0.36;
  var HORIZON_ROLL = 0.12;
  var SWELL_CELLS = 1.3;
  var LUMP_CELLS = 5.5;
  var HORIZON_SWELL_CELLS = 0.8;
  var HORIZON_LUMP_CELLS = 2.1;
  var DEPTH_FALL = 1.6;
  var DISTANCE_LANES = 3.1;
  var LUMP_SHARE = 0.34;
  var RIDGE_STEPS = 96;
  var OVERHANG = 40;
  var STONE_SMALLEST = 9;
  var STONE_LARGEST = 38;
  var STONE_SQUAT = 0.62;
  var STONE_LEAN = 0.5;
  var STONE_FAR = 0.3;
  var STONE_NEAR = 1;
  var STONE_SHRINK = 0.55;
  var RANGE_FAR = 0.08;
  var RANGE_NEAR = 0.75;
  var CLIFF_RISE_LEAST = 0.06;
  var CLIFF_RISE_SPAN = 0.16;
  var CLIFF_SPAN_LEAST = 0.12;
  var CLIFF_SPAN_SPAN = 0.26;
  var CLIFF_STEPS = 14;
  var CLIFF_DEEP = 0.05;
  var CLIFF_NEAR = 0.16;
  var MIN_SPAN7 = 1;
  var mix = (far, near, at) => far + (near - far) * at;
  function createSeabed(options) {
    var _a, _b, _c;
    const swell = makeNoise2(options.seed ^ 24235);
    const lumps = makeNoise2(options.seed ^ 4293);
    const random = makeRandom(options.seed ^ 11534);
    let width = Math.max(MIN_SPAN7, options.width);
    let height = Math.max(MIN_SPAN7, options.height);
    function floorAt(x, depth = 1) {
      const near = Math.max(0, Math.min(1, depth));
      const lane = (1 - near) * DISTANCE_LANES;
      const up = near ** DEPTH_FALL;
      const seat = height * (1 - mix(HORIZON_SEAT, FLOOR_SEAT, up));
      const roll = height * mix(HORIZON_ROLL, FLOOR_ROLL, up);
      const long = swell(x / width * mix(HORIZON_SWELL_CELLS, SWELL_CELLS, near), lane);
      const short = lumps(x / width * mix(HORIZON_LUMP_CELLS, LUMP_CELLS, near), lane + 4.7);
      return seat - (long * (1 - LUMP_SHARE) + short * LUMP_SHARE) * roll;
    }
    function cutRidge(depth) {
      const points = [];
      for (let at = 0; at <= RIDGE_STEPS; at++) {
        const x = -OVERHANG + at / RIDGE_STEPS * (width + OVERHANG * 2);
        points.push({ x, y: floorAt(x, depth) });
      }
      return points;
    }
    function cutRanges(count) {
      const bands = [];
      for (let at = 0; at < count; at++) {
        const depth = count < 2 ? RANGE_FAR : RANGE_FAR + at / (count - 1) * (RANGE_NEAR - RANGE_FAR);
        bands.push({ depth, ridge: cutRidge(depth) });
      }
      return bands;
    }
    function raise() {
      const middle = random() * width;
      const span = width * (CLIFF_SPAN_LEAST + random() * CLIFF_SPAN_SPAN);
      const rise = height * (CLIFF_RISE_LEAST + random() * CLIFF_RISE_SPAN);
      const rough = makeNoise2(random() * 65535 | 0);
      const depth = CLIFF_DEEP + random() * (CLIFF_NEAR - CLIFF_DEEP);
      const foot = floorAt(middle, depth);
      const ridge2 = [];
      for (let at = 0; at <= CLIFF_STEPS; at++) {
        const t = at / CLIFF_STEPS;
        const x = middle - span / 2 + t * span;
        const dome = (1 - Math.cos(t * Math.PI * 2)) / 2;
        const broken = 1 + rough(t * 3.1, 0) * 0.34;
        ridge2.push({ x, y: foot - rise * dome * broken });
      }
      return { depth, ridge: ridge2 };
    }
    function settle() {
      const x = random() * width;
      const depth = STONE_FAR + random() * (STONE_NEAR - STONE_FAR);
      const shrink = 1 - STONE_SHRINK + STONE_SHRINK * depth;
      const span = (STONE_SMALLEST + random() ** 1.5 * (STONE_LARGEST - STONE_SMALLEST)) * shrink;
      return {
        depth,
        lean: (random() - 0.5) * STONE_LEAN * 2,
        rise: span * STONE_SQUAT * (0.7 + random() * 0.6),
        span,
        x,
        y: floorAt(x, depth)
      };
    }
    let ridge = cutRidge(1);
    let ranges = cutRanges(Math.max(0, (_a = options.ranges) != null ? _a : 0));
    let cliffs = Array.from({ length: Math.max(0, (_b = options.cliffs) != null ? _b : 0) }, raise);
    let stones = Array.from({ length: Math.max(0, (_c = options.stones) != null ? _c : 0) }, settle);
    return {
      get cliffs() {
        return cliffs;
      },
      floorAt,
      get ranges() {
        return ranges;
      },
      /**
       * A resized box is rebuilt rather than scaled.
       *
       * Everything here is a pure function of the seed and the box, so rebuilding
       * gives the same bed the same box would have had from the start. Scaling
       * would stretch the sand's own grain, and a seabed that got wider when a
       * window did would be the one thing on screen admitting it is a drawing.
       */
      resize(nextWidth, nextHeight) {
        width = Math.max(MIN_SPAN7, nextWidth);
        height = Math.max(MIN_SPAN7, nextHeight);
        ridge = cutRidge(1);
        ranges = cutRanges(ranges.length);
        cliffs = cliffs.map(raise);
        stones = stones.map(settle);
      },
      get ridge() {
        return ridge;
      },
      get stones() {
        return stones;
      }
    };
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/sun.ts
  var RAD = Math.PI / 180;
  var J2000_OFFSET_DAYS = 10957.5;
  var DAY_MS = 864e5;
  var OBLIQUITY = 23.4397 * RAD;
  var REGION_LATITUDE = {
    Africa: 5,
    America: 38,
    Antarctica: -70,
    Arctic: 78,
    Asia: 30,
    Atlantic: 35,
    Australia: -30,
    Europe: 50,
    Indian: -15,
    Pacific: -20
  };
  var ZONE_LATITUDE = {
    "Africa/Cairo": 30,
    "Africa/Johannesburg": -26,
    "Africa/Lagos": 6,
    "Africa/Nairobi": -1,
    "America/Bogota": 5,
    "America/Lima": -12,
    "America/Santiago": -33,
    "America/Sao_Paulo": -23,
    "Asia/Jakarta": -6,
    "Asia/Kolkata": 22,
    "Asia/Singapore": 1,
    "Pacific/Auckland": -37,
    "Pacific/Fiji": -18,
    "Pacific/Honolulu": 21
  };
  function position(now) {
    var _a, _b, _c;
    const longitude = clamp2(-now.getTimezoneOffset() / 4, -180, 180);
    let zone = "";
    try {
      zone = (_a = Intl.DateTimeFormat().resolvedOptions().timeZone) != null ? _a : "";
    } catch (e) {
      zone = "";
    }
    const override = Object.entries(ZONE_LATITUDE).find(([name]) => zone.startsWith(name));
    if (override) return { latitude: override[1], longitude };
    const region = (_b = zone.split("/")[0]) != null ? _b : "";
    return { latitude: (_c = REGION_LATITUDE[region]) != null ? _c : 45, longitude };
  }
  function place(now, { latitude, longitude }) {
    const days = now.getTime() / DAY_MS - J2000_OFFSET_DAYS;
    const meanAnomaly = (357.5291 + 0.98560028 * days) * RAD;
    const eclipticLongitude = meanAnomaly + (1.9148 * Math.sin(meanAnomaly) + 0.02 * Math.sin(2 * meanAnomaly) + 3e-4 * Math.sin(3 * meanAnomaly)) * RAD + 102.9372 * RAD + Math.PI;
    const declination = Math.asin(Math.sin(eclipticLongitude) * Math.sin(OBLIQUITY));
    const rightAscension = Math.atan2(
      Math.sin(eclipticLongitude) * Math.cos(OBLIQUITY),
      Math.cos(eclipticLongitude)
    );
    const siderealTime = (280.16 + 360.9856235 * days) * RAD + longitude * RAD;
    const hourAngle = siderealTime - rightAscension;
    const phi = latitude * RAD;
    const altitude = Math.asin(
      Math.sin(phi) * Math.sin(declination) + Math.cos(phi) * Math.cos(declination) * Math.cos(hourAngle)
    );
    return { altitude: altitude / RAD, hourAngle };
  }
  function passage(hourAngle) {
    const wrapped = Math.atan2(Math.sin(hourAngle), Math.cos(hourAngle));
    const march = clamp2(0.5 + wrapped / Math.PI, 0, 1);
    return { arc: Math.sin(march * Math.PI), march };
  }
  function light(altitude) {
    return {
      daylight: clamp2((altitude + 6) / 12, 0, 1),
      dusk: clamp2(1 - Math.abs(altitude) / 8, 0, 1)
    };
  }
  function sunNow() {
    const now = /* @__PURE__ */ new Date();
    const { altitude, hourAngle } = place(now, position(now));
    return __spreadProps(__spreadValues({}, light(altitude)), {
      moon: passage(hourAngle + Math.PI),
      sun: passage(hourAngle)
    });
  }
  function clamp2(value, low, high) {
    return Math.min(high, Math.max(low, value));
  }
  return __toCommonJS(entry_exports);
})();
var OCTOPUS_HEAD = __ornament.OCTOPUS_HEAD
var createCephalopods = __ornament.createCephalopods
var octopusArms = __ornament.octopusArms
var squidArms = __ornament.squidArms
var squidBody = __ornament.squidBody
var createDrift = __ornament.createDrift
var frameAt = __ornament.frameAt
var SPAN = __ornament.SPAN
var STEPS = __ornament.STEPS
var CORAL = __ornament.CORAL
var createFlora = __ornament.createFlora
var HULL = __ornament.HULL
var PING_RINGS = __ornament.PING_RINGS
var SCREWS = __ornament.SCREWS
var SUBMARINE = __ornament.SUBMARINE
var SUB_SCREW = __ornament.SUB_SCREW
var WAKE = __ornament.WAKE
var createPassers = __ornament.createPassers
var ringAt = __ornament.ringAt
var SPREAD = __ornament.SPREAD
var createRays = __ornament.createRays
var BLOCK_CARD = __ornament.BLOCK_CARD
var BLOCK_LINES = __ornament.BLOCK_LINES
var CHEST_BANDS = __ornament.CHEST_BANDS
var CHEST_BODY = __ornament.CHEST_BODY
var CHEST_LOCK = __ornament.CHEST_LOCK
var LAPTOP_BASE = __ornament.LAPTOP_BASE
var LAPTOP_LINES = __ornament.LAPTOP_LINES
var LAPTOP_SCREEN = __ornament.LAPTOP_SCREEN
var SMOKER = __ornament.SMOKER
var SMOKER_LIP = __ornament.SMOKER_LIP
var WRECK = __ornament.WRECK
var WRECK_SPAR = __ornament.WRECK_SPAR
var createRelics = __ornament.createRelics
var createSeabed = __ornament.createSeabed
var SPECIES = __ornament.SPECIES
var WILD = __ornament.WILD
var createShoal = __ornament.createShoal
var daySeed = __ornament.daySeed
var freshSeed = __ornament.freshSeed
var sunNow = __ornament.sunNow

