.pragma library
// Generated by build-ornament.sh from the CodinCod repository. Do not edit.
if (!Array.prototype.at) {
  Array.prototype.at = function (index) {
    var i = Math.trunc(index) || 0
    if (i < 0) i += this.length
    return i < 0 || i >= this.length ? undefined : this[i]
  }
}
var __ornament = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // ../../../../../../tmp/tmp.n6qgW3KQRp/entry.ts
  var entry_exports = {};
  __export(entry_exports, {
    SPAN: () => SPAN,
    SPREAD: () => SPREAD,
    STEPS: () => STEPS,
    createDrift: () => createDrift,
    createRays: () => createRays,
    createShoal: () => createShoal,
    frameAt: () => frameAt,
    freshSeed: () => freshSeed
  });

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/perlin.ts
  var SIZE = 256;
  var MASK = SIZE - 1;
  var NORMALISE = Math.SQRT2;
  function makeRandom(seed) {
    let state = seed | 0 || 1;
    return () => {
      state ^= state << 13;
      state ^= state >>> 17;
      state ^= state << 5;
      return (state >>> 0) / 4294967296;
    };
  }
  function makeNoise2(seed) {
    const random = makeRandom(seed);
    const permutation = new Int32Array(SIZE + SIZE + 2);
    const gradientX = new Float64Array(SIZE + SIZE + 2);
    const gradientY = new Float64Array(SIZE + SIZE + 2);
    for (let i = 0; i < SIZE; i++) {
      permutation[i] = i;
      const angle = random() * Math.PI * 2;
      gradientX[i] = Math.cos(angle);
      gradientY[i] = Math.sin(angle);
    }
    for (let i = SIZE - 1; i > 0; i--) {
      const j = Math.floor(random() * (i + 1));
      const held = permutation[i];
      permutation[i] = permutation[j];
      permutation[j] = held;
    }
    for (let i = 0; i < SIZE + 2; i++) {
      permutation[SIZE + i] = permutation[i];
      gradientX[SIZE + i] = gradientX[i];
      gradientY[SIZE + i] = gradientY[i];
    }
    const dot = (gradient, x, y) => gradientX[gradient] * x + gradientY[gradient] * y;
    return (x, y) => {
      const cellX = Math.floor(x);
      const cellY = Math.floor(y);
      const dx0 = x - cellX;
      const dy0 = y - cellY;
      const dx1 = dx0 - 1;
      const dy1 = dy0 - 1;
      const bx0 = cellX & MASK;
      const by0 = cellY & MASK;
      const bx1 = bx0 + 1 & MASK;
      const by1 = by0 + 1 & MASK;
      const i = permutation[bx0];
      const j = permutation[bx1];
      const g00 = permutation[i + by0];
      const g10 = permutation[j + by0];
      const g01 = permutation[i + by1];
      const g11 = permutation[j + by1];
      const sx = sCurve(dx0);
      const sy = sCurve(dy0);
      const top = lerp(sx, dot(g00, dx0, dy0), dot(g10, dx1, dy0));
      const bottom = lerp(sx, dot(g01, dx0, dy1), dot(g11, dx1, dy1));
      return lerp(sy, top, bottom) * NORMALISE;
    };
  }
  function sCurve(t) {
    return t * t * (3 - 2 * t);
  }
  function lerp(t, a, b) {
    return a + t * (b - a);
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/drift.ts
  var FIELD_CELLS = 2.2;
  var DRIFT = 0.04;
  var SWAY = 13;
  var FALL_SLOWEST = 4;
  var FALL_FASTEST = 13;
  var MOTE_SMALLEST = 0.4;
  var MOTE_LARGEST = 1.9;
  var MOTE_BIAS = 2.6;
  var DEPTH_SIZE = 0.75;
  var DEPTH_NEAR = 1;
  var DEPTH_FAR = 0.08;
  var RISE_SLOWEST = 38;
  var RISE_FASTEST = 66;
  var BUBBLE_SMALLEST = 1.1;
  var BUBBLE_LARGEST = 2.9;
  var SWELL = 0.6;
  var WOBBLE = 9;
  var WOBBLE_RATE = 1.9;
  var VENT_RUN_LEAST = 0.7;
  var VENT_RUN_SPAN = 1.6;
  var VENT_REST_LEAST = 5;
  var VENT_REST_SPAN = 14;
  var VENT_GAP_LEAST = 0.07;
  var VENT_GAP_SPAN = 0.5;
  var MIN_SPAN = 1;
  function createDrift(options) {
    var _a, _b;
    const noise = makeNoise2(options.seed ^ 7487);
    const random = makeRandom(options.seed ^ 31265);
    let width = Math.max(MIN_SPAN, options.width);
    let height = Math.max(MIN_SPAN, options.height);
    let slide = 0;
    const floor = (_a = options.floor) != null ? _a : (() => height);
    const mote = () => {
      const depth = DEPTH_FAR + random() * (DEPTH_NEAR - DEPTH_FAR);
      const shrink = 1 - DEPTH_SIZE + DEPTH_SIZE * depth;
      return {
        depth,
        lane: random() * 200,
        r: (MOTE_SMALLEST + random() ** MOTE_BIAS * (MOTE_LARGEST - MOTE_SMALLEST)) * shrink,
        rate: (FALL_SLOWEST + random() * (FALL_FASTEST - FALL_SLOWEST)) * shrink,
        x: random() * width,
        y: random() * height
      };
    };
    const motes = Array.from({ length: Math.max(0, options.motes) }, mote);
    const vent = () => {
      const x = random() * width;
      return {
        next: 0,
        running: false,
        until: random() * (VENT_REST_LEAST + VENT_REST_SPAN),
        x,
        y: floor(x)
      };
    };
    const vents = Array.from({ length: Math.max(0, (_b = options.vents) != null ? _b : 0) }, vent);
    const bubbles = [];
    function release(from) {
      const depth = DEPTH_FAR + random() * (DEPTH_NEAR - DEPTH_FAR);
      bubbles.push({
        depth,
        lane: random() * 200,
        r: (BUBBLE_SMALLEST + random() * (BUBBLE_LARGEST - BUBBLE_SMALLEST)) * depth,
        rose: 0,
        x: from.x + (random() - 0.5) * WOBBLE,
        y: from.y
      });
    }
    return {
      bubbles,
      motes,
      resize(nextWidth, nextHeight, count) {
        const scaleX = Math.max(MIN_SPAN, nextWidth) / width;
        const scaleY = Math.max(MIN_SPAN, nextHeight) / height;
        width = Math.max(MIN_SPAN, nextWidth);
        height = Math.max(MIN_SPAN, nextHeight);
        for (const one of motes) {
          one.x *= scaleX;
          one.y *= scaleY;
        }
        for (const one of bubbles) {
          one.x *= scaleX;
          one.y *= scaleY;
        }
        if (count == null) return;
        while (motes.length > count) motes.pop();
        while (motes.length < count) motes.push(mote());
      },
      step(seconds) {
        const dt = Math.min(Math.max(seconds, 0), 0.1);
        slide += DRIFT * dt;
        const scale = FIELD_CELLS / width;
        for (const one of motes) {
          const push = noise(one.x * scale + one.lane, one.y * scale + one.lane + slide);
          one.x += push * SWAY * one.depth * dt;
          one.y += one.rate * dt;
          if (one.y > height + one.r) {
            one.y = -one.r;
            one.x = random() * width;
          }
          one.x = around(one.x, width, one.r);
        }
        for (const from of vents) {
          from.until -= dt;
          if (from.until <= 0) {
            from.running = !from.running;
            from.until = from.running ? VENT_RUN_LEAST + random() * VENT_RUN_SPAN : VENT_REST_LEAST + random() * VENT_REST_SPAN;
            from.next = 0;
          }
          if (!from.running) continue;
          from.next -= dt;
          if (from.next > 0) continue;
          from.next = VENT_GAP_LEAST + random() * VENT_GAP_SPAN;
          release(from);
        }
        for (let at = bubbles.length - 1; at >= 0; at--) {
          const one = bubbles[at];
          if (!one) continue;
          const climb = (RISE_SLOWEST + one.depth * (RISE_FASTEST - RISE_SLOWEST)) * one.depth;
          one.rose += dt;
          one.y -= climb * dt;
          one.r += one.r * SWELL * (climb / Math.max(height, MIN_SPAN)) * dt;
          one.x += Math.cos(one.rose * WOBBLE_RATE + one.lane) * WOBBLE * dt;
          if (one.y + one.r < 0) bubbles.splice(at, 1);
        }
      }
    };
  }
  function around(value, span, margin) {
    if (value > span + margin) return -margin;
    if (value < -margin) return span + margin;
    return value;
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/fish_shape.ts
  var SPAN = 38;
  var NOSE = 29;
  var along = (t) => 21 * t * (1 - t) ** 2 + 63 * t ** 2 * (1 - t) + 29 * t ** 3;
  var half = (t) => 24 * t * (1 - t) + WRIST * (1 - t);
  var WRIST = 1.4;
  var STATIONS = 20;
  var SWEEP = 0.2;
  var WAVES = 0.85;
  var TWIST = 2 * Math.PI * WAVES;
  var envelope = (u) => 0.2 - 0.8 * u + 1.6 * u * u;
  var wave = (u, phase) => envelope(u) * Math.sin(TWIST * u - phase);
  var SLOPE = 0.6;
  var FLUKE_BACK = -9;
  var FLUKE_SPREAD = 7;
  var FLUKE_NOTCH = -7;
  var SAMPLES = 90;
  function reach(amp) {
    let low = Number.POSITIVE_INFINITY;
    let high = Number.NEGATIVE_INFINITY;
    for (let at = 0; at < SAMPLES; at++) {
      const phase = at / SAMPLES * 2 * Math.PI;
      const sway = (x) => amp * wave(1 - x / NOSE, phase);
      const angle = Math.atan2(sway(SLOPE) - sway(-SLOPE), 2 * SLOPE);
      const tip = sway(0) + FLUKE_BACK * Math.sin(angle);
      low = Math.min(low, tip);
      high = Math.max(high, tip);
    }
    return high - low;
  }
  function fitted() {
    let amp = SWEEP * SPAN;
    for (let pass = 0; pass < 8; pass++) amp *= SWEEP * SPAN / reach(amp);
    return amp;
  }
  var AMP = fitted();
  function spine(x, phase) {
    return AMP * wave(1 - x / NOSE, phase);
  }
  function station(x, phase) {
    const back = spine(x - SLOPE, phase);
    const front = spine(x + SLOPE, phase);
    return { angle: Math.atan2(front - back, 2 * SLOPE), x, y: spine(x, phase) };
  }
  var clear = (on, lift) => [
    on.x + Math.sin(on.angle) * lift,
    on.y - Math.cos(on.angle) * lift
  ];
  var above = (x, lift, phase) => clear(station(x, phase), lift);
  var fixed = (value) => value.toFixed(2);
  function rounded(points) {
    const mid = (a, b) => `${fixed((a[0] + b[0]) / 2)} ${fixed((a[1] + b[1]) / 2)}`;
    const last = points[points.length - 1];
    let d = `M${mid(last, points[0])}`;
    for (let at = 0; at < points.length; at++) {
      const here = points[at];
      const next = points[(at + 1) % points.length];
      d += `Q${fixed(here[0])} ${fixed(here[1])} ${mid(here, next)}`;
    }
    return `${d}Z`;
  }
  var fin = (points) => `M${points.map(([x, y]) => `${fixed(x)} ${fixed(y)}`).join("L")}Z`;
  function dorsal(phase) {
    const foot = (t, over) => {
      const x = along(t);
      return clear(station(x, phase), half(t) + over);
    };
    return fin([foot(0.38, -SET), foot(0.52, TIP), foot(0.66, -SET)]);
  }
  var SET = 0.8;
  var TIP = 5;
  function outline(phase) {
    const top = [];
    const bottom = [];
    for (let at = 0; at <= STATIONS; at++) {
      const t = at / STATIONS;
      const x = along(t);
      const on = station(x, phase);
      const lift = half(t);
      top.push(clear(on, lift));
      bottom.push(clear(on, -lift));
    }
    return [...top, ...bottom.reverse()];
  }
  var ROOT = 2.5;
  function tail(phase) {
    const joint = station(0, phase);
    const cos = Math.cos(joint.angle);
    const sin = Math.sin(joint.angle);
    const carry = ([x, y]) => [
      joint.x + x * cos - y * sin,
      joint.y + x * sin + y * cos
    ];
    return fin([
      carry([ROOT, 0]),
      carry([FLUKE_BACK, FLUKE_SPREAD]),
      carry([FLUKE_NOTCH, 0]),
      carry([FLUKE_BACK, -FLUKE_SPREAD])
    ]);
  }
  var STEPS = 48;
  var drawn = new Array(STEPS);
  var EYE_R = 1.5;
  var EYE_X = 22;
  var EYE_LIFT = 2;
  function build(at) {
    const phase = at / STEPS * 2 * Math.PI;
    const [x, y] = above(EYE_X, EYE_LIFT, phase);
    return {
      at,
      d: rounded(outline(phase)) + tail(phase) + dorsal(phase),
      eye: { r: EYE_R, x, y }
    };
  }
  function frameAt(phase) {
    const at = (Math.round(phase / (2 * Math.PI) * STEPS) % STEPS + STEPS) % STEPS;
    const had = drawn[at];
    if (had) return had;
    const made = build(at);
    drawn[at] = made;
    return made;
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/rays.ts
  var SPREAD = 2.4;
  var SPAN_LEAST = 0.018;
  var SPAN_SPAN = 0.055;
  var REACH_LEAST = 0.45;
  var REACH_SPAN = 0.5;
  var TILT = 0.16;
  var TILT_SPREAD = 0.07;
  var GLOW_LEAST = 0.25;
  var GLOW_MOST = 1;
  var BREATH_SLOWEST = 0.045;
  var BREATH_FASTEST = 0.11;
  var WANDER = 26;
  var WANDER_RATE = 0.06;
  var MIN_SPAN2 = 1;
  function createRays(options) {
    const random = makeRandom(options.seed ^ 13239);
    let width = Math.max(MIN_SPAN2, options.width);
    let height = Math.max(MIN_SPAN2, options.height);
    let clock = 0;
    const breaths = [];
    const rays = [];
    function born() {
      breaths.push({
        at: random() * Math.PI * 2,
        rate: BREATH_SLOWEST + random() * (BREATH_FASTEST - BREATH_SLOWEST),
        seat: random() * Math.PI * 2
      });
      return {
        glow: GLOW_LEAST,
        reach: height * (REACH_LEAST + random() * REACH_SPAN),
        span: width * (SPAN_LEAST + random() * SPAN_SPAN),
        tilt: TILT + (random() - 0.5) * TILT_SPREAD,
        x: random() * width
      };
    }
    for (let made = 0; made < Math.max(0, options.count); made++) rays.push(born());
    return {
      rays,
      resize(nextWidth, nextHeight, count) {
        const scaleX = Math.max(MIN_SPAN2, nextWidth) / width;
        width = Math.max(MIN_SPAN2, nextWidth);
        height = Math.max(MIN_SPAN2, nextHeight);
        for (const one of rays) one.x *= scaleX;
        if (count == null) return;
        while (rays.length > count) {
          rays.pop();
          breaths.pop();
        }
        while (rays.length < count) rays.push(born());
      },
      step(seconds) {
        clock += Math.min(Math.max(seconds, 0), 0.1);
        for (let at = 0; at < rays.length; at++) {
          const one = rays[at];
          const breath = breaths[at];
          if (!one || !breath) continue;
          const swell = (Math.sin(breath.at + clock * breath.rate * Math.PI * 2) + 1) / 2;
          one.glow = GLOW_LEAST + swell * (GLOW_MOST - GLOW_LEAST);
          one.x += Math.cos(breath.seat + clock * WANDER_RATE * Math.PI * 2) * WANDER * seconds;
        }
      }
    };
  }

  // ../../../../Documents/projects/codincodv2/assets/js/ornament/shoal.ts
  var MIN_SHOAL = 1;
  var FIELD_CELLS2 = 3.6;
  var DRIFT2 = 0.06;
  var CRUISE = 1.05;
  var STRIDE = 0.7;
  var DART = 3.4;
  var TURN = 0.85;
  var TURN_STARTLED = 3.4;
  var HASTE = 2.2;
  var MAX_PITCH = 0.6;
  var EDGE_REACH = 0.18;
  var EDGE_PUSH = 0.9;
  var SWEEP2 = 1.1;
  var HOMING = 0.34;
  var HOLD_LEAST = 1.6;
  var HOLD_SPAN = 6.5;
  var BEND = 0.85;
  var WOBBLE2 = 0.18;
  var MARGIN = 0.8;
  var NEIGHBOUR_REACH = 70;
  var NEIGHBOUR_PUSH = 0.8;
  var FLEE_REACH = 340;
  var FLEE_PUSH = 3.6;
  var PANIC = 0.62;
  var LOOK_DELAY = 1.1;
  var LOOK_REACH = 320;
  var LOOK_PUSH = 2.2;
  var LEAN_PUSH = 0.5;
  var LOOK_SPAN = 13;
  var LOOK_REST = 5;
  var STANDOFF = 70;
  var HOVER = 0.45;
  var LOSE_INTEREST = 1.8;
  var DEPTH_MID = 0.52;
  var DEPTH_SWING = 0.46;
  var DEPTH_DRIFT = 0.035;
  var DEPTH_NEAR2 = 1;
  var DEPTH_FAR2 = 0.06;
  var DEPTH_EASE = 0.5;
  var DEPTH_DIVE = 1.4;
  var DIVE = 0.35;
  var RISE = 0.94;
  var DEPTH_SIZE2 = 0.6;
  var SURGE = 0.26;
  var SLOWEST = 0.45;
  var FASTEST = 1.9;
  var LEISURE = 2;
  var SHORTEST = 34;
  var LONGEST = 58;
  function freshSeed(from = 0) {
    let seed = (Date.now() ^ from) >>> 0;
    seed = Math.imul(seed ^ seed >>> 16, 73244475) >>> 0;
    return (seed ^ seed >>> 16) >>> 0;
  }
  function createShoal(options) {
    var _a, _b, _c;
    const noise = makeNoise2(options.seed);
    const depths = makeNoise2(options.seed ^ 40503);
    const random = makeRandom(options.seed ^ 24381);
    let width = Math.max(1, options.width);
    let height = Math.max(1, options.height);
    let drift = 0;
    let sank = 0;
    let still = 0;
    let attentive = null;
    let visit = 0;
    let rest = 0;
    let last = null;
    const cruise = (_a = options.cruise) != null ? _a : CRUISE;
    const shortest = (_b = options.shortest) != null ? _b : SHORTEST;
    const longest = (_c = options.longest) != null ? _c : LONGEST;
    const born = () => spawn(random, { cruise, height, longest, shortest, width });
    const fish = Array.from({ length: Math.max(MIN_SHOAL, options.count) }, born);
    return {
      get attentive() {
        return attentive;
      },
      fish,
      resize(nextWidth, nextHeight, count) {
        const scaleX = Math.max(1, nextWidth) / width;
        const scaleY = Math.max(1, nextHeight) / height;
        width = Math.max(1, nextWidth);
        height = Math.max(1, nextHeight);
        for (const one of fish) {
          one.x *= scaleX;
          one.y *= scaleY;
        }
        if (count == null) return;
        while (fish.length > count && fish.length > MIN_SHOAL) {
          if (fish.at(-1) === attentive) attentive = null;
          fish.pop();
        }
        while (fish.length < count) fish.push(born());
      },
      step(seconds, pointer) {
        const dt = Math.min(Math.max(seconds, 0), 0.1);
        drift += DRIFT2 * dt;
        sank += DEPTH_DRIFT * dt;
        still = pointer && !pointer.moving ? still + dt : 0;
        const looking = still > LOOK_DELAY;
        const fleeing = (pointer == null ? void 0 : pointer.moving) === true;
        if (!looking || !pointer) {
          attentive = null;
          last = null;
          rest = 0;
          visit = 0;
        } else if (attentive) {
          visit += dt;
          const strayed = away(attentive, pointer) > LOOK_REACH * LOSE_INTEREST || away(attentive, pointer) > STANDOFF && !ahead(attentive, pointer);
          if (visit > LOOK_SPAN || strayed) {
            last = attentive;
            attentive = null;
            visit = 0;
            rest = LOOK_REST;
          }
        } else if (rest > 0) {
          rest -= dt;
        } else {
          attentive = nearest(fish, pointer, LOOK_REACH, last);
        }
        for (const one of fish) {
          one.hold -= dt;
          if (one.hold <= 0) decide(one, random, height);
          one.lean = ease(one.lean, one.aim, BEND * dt);
          const startled = fleeing && pointer != null && away(one, pointer) < FLEE_REACH * PANIC;
          const [wantX, wantY] = want(
            one,
            fish,
            noise,
            drift,
            looking ? pointer : null,
            fleeing ? pointer : null,
            one === attentive,
            width,
            height
          );
          one.heading = toward(
            one.heading,
            steady(one.facing, Math.atan2(wantY, wantX)),
            startled ? AGILITY_BOLT : AGILITY,
            startled ? TURN_STARTLED : TURN,
            dt
          );
          const ambient = clamp(
            DEPTH_MID + DEPTH_SWING * depths(one.lane, sank),
            DEPTH_FAR2,
            DEPTH_NEAR2
          );
          const wanted = startled ? ambient * DIVE : one === attentive ? RISE : ambient;
          one.depth = ease(one.depth, wanted, (startled ? DEPTH_DIVE : DEPTH_EASE) * dt);
          one.size = one.length * (1 - DEPTH_SIZE2 + DEPTH_SIZE2 * one.depth);
          const hovering = one === attentive && pointer && away(one, pointer) < STANDOFF;
          const wants = cruise * one.pace * one.size * (startled ? DART : hovering ? HOVER : 1);
          one.speed = ease(one.speed, wants, HASTE * dt);
          one.tail += 2 * Math.PI * one.speed / (STRIDE * one.size) * dt;
          const stroke = one.speed * (1 + SURGE * Math.cos(2 * one.tail));
          one.x = around2(one.x + Math.cos(one.heading) * stroke * dt, width, one.size);
          one.y = clamp(one.y + Math.sin(one.heading) * stroke * dt, -EDGE_HOLD, height + EDGE_HOLD);
        }
      }
    };
  }
  function want(one, shoal, noise, drift, looking, fleeing, attentive, width, height) {
    const scale = FIELD_CELLS2 / width;
    const nx = one.x * scale + drift * 0.3;
    const ny = one.y * scale + drift;
    const pitched = one.lean + noise(nx + one.lane, ny + one.lane) * WOBBLE2;
    let x = one.facing * Math.cos(pitched);
    let y = Math.sin(pitched);
    const reach2 = height * EDGE_REACH;
    y += edge(one.y, reach2) - edge(height - one.y, reach2);
    for (const other of shoal) {
      if (other === one) continue;
      const [awayX, awayY, distance] = separation(one, other);
      if (distance >= NEIGHBOUR_REACH) continue;
      const t = 1 - distance / NEIGHBOUR_REACH;
      const push = t * t * (3 - 2 * t) * NEIGHBOUR_PUSH / Math.max(distance, 0.5);
      x += awayX * push;
      y += awayY * push;
    }
    if (fleeing) {
      const [awayX, awayY, distance] = separation(one, fleeing);
      if (distance < FLEE_REACH) {
        const push = (FLEE_REACH - distance) / FLEE_REACH * FLEE_PUSH / Math.max(distance, 0.5);
        x += awayX * push;
        y += awayY * push;
      }
    }
    if (looking) {
      const [awayX, awayY, distance] = separation(one, looking);
      const push = attentive ? LOOK_PUSH : distance < LOOK_REACH ? LEAN_PUSH : 0;
      if (push > 0) {
        x -= awayX / Math.max(distance, 0.5) * push;
        y -= awayY / Math.max(distance, 0.5) * push;
      }
    }
    return [x, y];
  }
  function spawn(random, box) {
    const facing = random() < 0.5 ? -1 : 1;
    const aim = (random() - 0.5) * SWEEP2;
    const depth = DEPTH_FAR2 + random() * (DEPTH_NEAR2 - DEPTH_FAR2);
    const length = box.shortest + random() * (box.longest - box.shortest);
    const pace = SLOWEST + random() ** LEISURE * (FASTEST - SLOWEST);
    const size = length * (1 - DEPTH_SIZE2 + DEPTH_SIZE2 * depth);
    return {
      aim,
      depth,
      facing,
      heading: steady(facing, aim),
      hold: random() * (HOLD_LEAST + HOLD_SPAN),
      lane: random() * 200,
      lean: aim,
      length,
      pace,
      size,
      speed: box.cruise * pace * size,
      tail: random() * Math.PI * 2,
      x: random() * box.width,
      y: random() * box.height
    };
  }
  function nearest(shoal, to, reach2, over) {
    let closest = null;
    let best = reach2;
    let spare = null;
    for (const one of shoal) {
      const distance = away(one, to);
      if (distance >= best || !ahead(one, to)) continue;
      if (one === over) {
        spare = one;
        continue;
      }
      best = distance;
      closest = one;
    }
    return closest != null ? closest : spare;
  }
  function ahead(one, to) {
    return (to.x - one.x) * Math.cos(one.heading) + (to.y - one.y) * Math.sin(one.heading) > 0;
  }
  var away = (one, to) => Math.hypot(one.x - to.x, one.y - to.y);
  function separation(one, to) {
    const x = one.x - to.x;
    const y = one.y - to.y;
    return [x, y, Math.hypot(x, y)];
  }
  function decide(one, random, height) {
    const roll = random() * 2 - 1;
    const homing = -((one.y / Math.max(height, 1) - 0.5) * 2) * HOMING;
    one.aim = clamp(homing + roll * Math.abs(roll) * SWEEP2, -MAX_PITCH, MAX_PITCH);
    one.hold = HOLD_LEAST + random() * HOLD_SPAN;
  }
  function toward(from, to, gain, most, dt) {
    let by = (to - from) % (Math.PI * 2);
    if (by > Math.PI) by -= Math.PI * 2;
    if (by < -Math.PI) by += Math.PI * 2;
    const rate = Math.max(-most, Math.min(most, by * gain));
    return from + rate * dt;
  }
  var AGILITY = 1.5;
  var AGILITY_BOLT = 4.2;
  function steady(facing, want2) {
    const asked = Math.atan2(Math.sin(want2), facing * Math.cos(want2));
    const rel = MAX_PITCH * Math.tanh(asked / MAX_PITCH);
    return facing > 0 ? rel : Math.PI - rel;
  }
  var ease = (from, to, rate) => from + (to - from) * Math.min(1, Math.max(0, rate));
  function edge(distance, reach2) {
    if (reach2 <= 0 || distance >= reach2) return 0;
    return (reach2 - distance) / reach2 * EDGE_PUSH;
  }
  var clamp = (value, low, high) => Math.min(Math.max(value, low), high);
  function around2(value, span, body) {
    const margin = body * MARGIN;
    if (value > span + margin) return -margin;
    if (value < -margin) return span + margin;
    return value;
  }
  var EDGE_HOLD = 8;
  return __toCommonJS(entry_exports);
})();
var createDrift = __ornament.createDrift
var createRays = __ornament.createRays
var createShoal = __ornament.createShoal
var frameAt = __ornament.frameAt
var freshSeed = __ornament.freshSeed
var SPAN = __ornament.SPAN
var SPREAD = __ornament.SPREAD
var STEPS = __ornament.STEPS
